### PR TITLE
Removed line numbers in code block

### PR DESCRIPTION
**Pull request by Alspb**
# Pull Request

## Description

Removes line number from the code block.

## Issues

Fixes the following problems:

- Code block line numbers interferes with ordered lists. For instance, in the example "Have trouble finding things?" line has No. 2 instead of 1 because of the code block above.
- Text in code block override line numbers anyway.

## Improvements

Removing line numbers also saves some space on mobile screens.
Finally, code blocks simply don't need line numbers, it's not an IDE.

## Checklist

- [ ] I have added/updated relevant documentation 
- [ ] I have tested these changes locally. 
- [ ] I have followed the code style and guidelines. 
- [ ] I have updated `CHANGELOG.md` with my changes in the next section 
- [ ] I have run `dart format .`` on the project 
- [ ] I have run `dart fix --apply` on the project 
- [ ] I have run `flutter test` and `flutter analyze` and it passed successfully 
- [ ] I have run `./before-push.sh` and everything is fine

### CODE REVIEW

**Comment by singerdmx** [comment]
Maybe add condition to check platform?

**Comment by singerdmx** [comment]
@freshtechtips what do you think?

**Comment by freshtechtips** [comment]
> # Pull Request
> ## Description
> Removes line number from the code block.
> 
> ## Issues
> Fixes the following problems:
> 
> * Code block line numbers interferes with ordered lists. For instance, in the example "Have trouble finding things?" line has No. 2 instead of 1 because of the code block above.
> * Text in code block override line numbers anyway.
> 
> ## Improvements
> Removing line numbers also saves some space on mobile screens. Finally, code blocks simply don't need line numbers, it's not an IDE.
> 
> ## Checklist
> * [ ]  I have added/updated relevant documentation
> * [ ]  I have tested these changes locally.
> * [ ]  I have followed the code style and guidelines.
> * [ ]  I have updated `CHANGELOG.md` with my changes in the next section
> * [ ]  I have run `dart format .`` on the project
> * [ ]  I have run `dart fix --apply` on the project
> * [ ]  I have run `flutter test` and `flutter analyze` and it passed successfully
> * [ ]  I have run `./before-push.sh` and everything is fine

So we can no longer add a numbered list in the code block??
Please provide us a short video before/after, it would help a lot since I'm in the middle of some process and can't think enough about this

or at least a image

**Comment by freshtechtips** [comment]
> @freshtechtips what do you think?

If it buggy then sure we will remove the support for it but luckily we still can give the developer the option to use this feature without remove it, we will disable it by default in the editor configurations but it will be possible to enable it again by developer choice

**Comment by freshtechtips** [comment]
> @freshtechtips what do you think?

let's solve this real quick and we will do it in one update by publishing the package changes

**Comment by singerdmx** [comment]
I think you can merge it if you want

**Comment by freshtechtips** [comment]
> I think you can merge it if you want

I will. but I need more details from @Alspb is possible

**Comment by freshtechtips** [comment]
> # Pull Request
> ## Description
> Removes line number from the code block.
> 
> ## Issues
> Fixes the following problems:
> 
> * Code block line numbers interferes with ordered lists. For instance, in the example "Have trouble finding things?" line has No. 2 instead of 1 because of the code block above.
> * Text in code block override line numbers anyway.
> 
> ## Improvements
> Removing line numbers also saves some space on mobile screens. Finally, code blocks simply don't need line numbers, it's not an IDE.
> 
> ## Checklist
> * [ ]  I have added/updated relevant documentation
> * [ ]  I have tested these changes locally.
> * [ ]  I have followed the code style and guidelines.
> * [ ]  I have updated `CHANGELOG.md` with my changes in the next section
> * [ ]  I have run `dart format .`` on the project
> * [ ]  I have run `dart fix --apply` on the project
> * [ ]  I have run `flutter test` and `flutter analyze` and it passed successfully
> * [ ]  I have run `./before-push.sh` and everything is fine

I can't encounter the issue that you solved. Please give us details instructions on how to encounter it if possible

Thank you for the report

**Comment by freshtechtips** [comment]
Thanks. I'm able to encounter the issue on any platform other than web, I will make an update and solve this in different way because I want to provide the option to whatever enable line numbers in code block or not

**Comment by freshtechtips** [comment]
@singerdmx I making some changes to solve this issue but I have a question

can we consider everything in the editor every single element as a block?? image block? text block etc..
if there is a better naming, please suggest it

**Comment by singerdmx** [comment]
> @singerdmx I making some changes to solve this issue but I have a question
> 
> 
> 
> can we consider everything in the editor every single element as a block?? image block? text block etc..
> 
> if there is a better naming, please suggest it

What new design do you propose?

**Comment by freshtechtips** [comment]
> Here are both bugs on one screenshot:
> 
> code_block_line_numbers_bugs

The changes you made are just removing the line numbers in the code block right?? please let me know if you made more changes because I'm solving this in different way, by give the option to enable it in the new configurations

**Comment by freshtechtips** [comment]
> > @singerdmx I making some changes to solve this issue but I have a question
> > can we consider everything in the editor every single element as a block?? image block? text block etc..
> > if there is a better naming, please suggest it
> 
> What new design do you propose?

I'm not refactoring the blocks. I'm just adding a new class configurations in the quill editor configurations for the code block to configure if this line numbers is disabled or not in code block

I want to know if everything can be consider as blocks in the editor

**Pull request merged**
