### PR TITLE
Flutter version compatibility

### PR DESCRIPTION
**Pull request by MagTuxGit**
https://github.com/singerdmx/flutter-quill/issues/516

### CODE REVIEW

**Comment by MagTuxGit** [comment]
@singerdmx Why did you lower it back?
https://github.com/singerdmx/flutter-quill/commit/49040447b12797127ac3882978329f806b639ab5

**Comment by singerdmx** [comment]
Pub dev is not ready

**Comment by singerdmx** [comment]
Pub dev does not work with 2.8
Our score become 60 instead of 120

**Comment by MagTuxGit** [comment]
Got it

**Pull request merged**
