### PR TITLE
Text magnification feature

### PR DESCRIPTION
**Pull request by ellet0**
[Feature request](https://github.com/singerdmx/flutter-quill/issues/1504)

This pull request is not ready yet and can't done any time soon

We need a better understanding of the Core Quill library and it requires too much time
unfortunately, I don't have it right now so I will focus on other things for now

But it would be great if anyone wants to implement this feature

### CODE REVIEW

**Comment by singerdmx** [comment]
@li3317 if you have time, please take a look

**Comment by freshtechtips** [comment]
> @li3317 if you have time, please take a look

Also, feel free to take a look at [this](https://github.com/singerdmx/flutter-quill/issues/1504#issuecomment-1802223052)

For more info, we discussed at a little bit in the feature request

**Comment by fdwl** [comment]
I would like to express my appreciation for the excellent feature that has been added. This feature is exactly what I have been eagerly anticipating and it fulfills a crucial need for me. Thank you for your hard work and dedication in delivering such a valuable functionality. 👍👍👍👍👍

**Comment by freshtechtips** [comment]
> I would like to express my appreciation for the excellent feature that has been added. This feature is exactly what I have been eagerly anticipating and it fulfills a crucial need for me. Thank you for your hard work and dedication in delivering such a valuable functionality. 👍👍👍👍👍

Hi, I appreciate your support but we haven't really done it yet and we can't do it without asking some questions the old maintainers of QuillRawEditor

So we don't want to disappoint you

**Pull request closed without merging**
