### PR TITLE
Add custom toolbar for photo and video.

### PR DESCRIPTION
**Pull request by shoridevel**
I changed the dialog for photos and videos to be customizable.
It can be executed by uncommenting cameraPickSettingSelector: _selectCameraPickSetting.

### CODE REVIEW

**Comment by singerdmx** [comment]
Too many issues with this change. I have to revert it

**Comment by singerdmx** [comment]
A couple of things I found:
1. please don't create new file camera_video_utils.dart. Too many duplicates there. Please refactor your logic into image_video_utils.dart.
2. You need to add `await`
image


3. Please fix all dart analysis warnings such as import order.

**Comment by singerdmx** [comment]
Your code cause app not able to load. Not sure why

**Comment by singerdmx** [comment]
If you have better dialog, **just replace the default one**.
Not need to extend it to `custom`

**Comment by singerdmx** [comment]
Ahh, I think the break is caused by https://github.com/singerdmx/flutter-quill/pull/900

**Comment by shoridevel** [comment]
Sorry, I got it. I'll try again.

**Pull request merged**
