### PR TITLE
My custom changes

### PR DESCRIPTION
**Pull request by Abbas1Hussein**
Subject: Feature Proposal: Support for flutter_quill_extensions_lite

---

Hi there,

I hope this message finds you well. I have developed an additional package called `flutter_quill_extensions_lite`, which enhances the functionality of the `flutter_quill` package by providing extra features. To make this package work seamlessly, a few changes are required in the `flutter_quill` codebase.

I have made the necessary modifications to enable compatibility with `flutter_quill_extensions_lite`. These changes are essential for the successful deployment and utilization of the new package.

You can find the new package repository here: [flutter_quill_extensions_lite](https://github.com/Abbas1Hussein/flutter_quill_extensions_lite). It would be fantastic if these changes could be reviewed and merged into the `flutter_quill` repository.

Thank you for your time and consideration. I'm looking forward to your feedback.

Best regards,
[Abbas Hussein]

### CODE REVIEW

**Comment by singerdmx** [comment]
Please format code

**Comment by singerdmx** [comment]
I think adding a new attribute needs to conform to the quill standard.
And your change is missing a lot of places for new attribute. Please check how other attribute is being used.
I am not sure data is the right key here unless you have other places doing such practice.

**Comment by Abbas1Hussein** [comment]
Subject: Proposal and Clarification of Changes to Support New Attribute in flutter_quill

I wanted to provide some additional context and clarification regarding the recent changes I proposed for the `flutter_quill` package.

I've created a video demonstration to showcase the changes I've made. You can watch the video [here](https://drive.google.com/file/d/1Kxy-dLocXMxWT8NL-5p2TiBMZ2JF12bh/view?usp=drive_link). This video provides a visual overview of how the `data` attribute works and its benefits.

To better understand the changes and their impact, I'd like to invite you to try out the updated package. You can test the changes by adding the following lines to your `pubspec.yaml`:

```yaml
dependencies:
  flutter_quill:
    git:
      url: https://github.com/Abbas1Hussein/flutter-quill.git
      ref: my-custom-changes

  flutter_quill_extensions_lite:
    git:
      url: https://github.com/Abbas1Hussein/flutter_quill_extensions_lite.git
```

This will allow you to experience the changes firsthand and explore how the `flutter_quill_extensions_lite` package enhances the functionality of the `flutter_quill` package.

Regarding the `data` attribute, I want to assure you that I've taken measures to ensure its seamless integration without affecting the existing attributes. Its primary purpose is to efficiently save data for elements like boxes and tables, enhancing the package's capabilities.

I also addressed an issue related to the usage of the `AttributeScope` parameter. By not utilizing the `AttributeScope` parameter as `INLINE`, I encountered an error when applying styles to leaf elements. My changes effectively resolve this issue, resulting in a smoother user experience.

Additionally, I've implemented a feature that empowers users to customize the view of embed elements. As an example, I've included a `boxBuilder` that allows users to define a custom view for the `box` element. This level of customization empowers users to tailor the appearance and behavior of embedded elements according to their unique requirements.

Here's an example of how the `boxBuilder` could be used:

```dart
embedBuilders: FlutterQuillEmbeds.builders(
  boxBuilder: (attributes, value, showEditDialog, readOnly) {
    if (readOnly) {
      return Card(child: Text(value));
    } else {
      return GestureDetector(
        onTap: () => showEditDialog,
        child: Card(child: Text(value, style: attributes.style)),
      );
    }
  },
),
```

I genuinely believe that these changes align with the goals of the `flutter_quill` package and contribute positively to its functionality.

I'm open to any feedback or suggestions you may have regarding these changes. Your insights are invaluable, and I'm committed to ensuring that these modifications adhere to the package's standards.

Thank you for your time and consideration. I'm looking forward to your thoughts on these clarifications.

Best regards,
[ِAbbas Hussein]

**Comment by singerdmx** [comment]
It is not up to you to define the schema or data structure. Quill already defined it.

**Comment by Abbas1Hussein** [comment]
I appreciate your attention to the schema and data structure defined by Quill.

I completely understand the importance of maintaining consistency and adhering to the established schema. My intention in introducing the `data` attribute was to enhance the existing functionality of Quill by providing a means to efficiently save data for specific elements like boxes and tables. While I aimed to contribute to the package's capabilities, I acknowledge the significance of adhering to the schema that Quill has already defined.

I want to assure you that my proposed changes were driven by the desire to extend Quill's capabilities within the framework of its existing schema. I'm committed to collaborating closely with you and the Quill community to ensure that any modifications align with the package's standards and schema.

If there are specific concerns or adjustments you would like to discuss regarding the introduction of the `data` attribute, I am more than willing to address them. Your insights and expertise are valuable, and I want to ensure that any contributions I make are in harmony with Quill's design principles.

Thank you again for your guidance, and I look forward to your further input on this matter.

**Comment by singerdmx** [comment]
https://quilljs.com/guides/designing-the-delta-format/

**Review by singerdmx — CHANGES_REQUESTED** [review]
We already have image

**Comment by singerdmx** [comment]
In Quill.js, creating tables using deltas involves a slightly more complex structure due to the nature of tables. Tables are composed of rows, and each row contains cells. To represent tables in deltas, you need to use a combination of nested inserts and attributes. Here's an example of how you might structure a table in Quill.js delta format:

```
{
  "ops": [
    {
      "insert": {
        "table": {
          "rows": [
            [
              { "insert": "Header 1", "attributes": { "bold": true } },
              { "insert": "Header 2", "attributes": { "bold": true } },
              { "insert": "Header 3", "attributes": { "bold": true } }
            ],
            [
              { "insert": "Row 1, Cell 1" },
              { "insert": "Row 1, Cell 2" },
              { "insert": "Row 1, Cell 3" }
            ],
            [
              { "insert": "Row 2, Cell 1" },
              { "insert": "Row 2, Cell 2" },
              { "insert": "Row 2, Cell 3" }
            ]
          ]
        }
      }
    }
  ]
}

```

In this example, the ops array contains a single operation that inserts a table. The table is represented using an object with a rows property, which is an array containing rows. Each row is an array of cells, where each cell is represented using an insert operation. You can also include attributes for each cell to apply formatting or styling.

Remember that while Quill.js doesn't provide native support for tables, you can implement a module or custom logic to handle table creation, modification, and rendering based on this structure.

**Comment by singerdmx** [comment]
> We already have image

Please don't add image support as we already have it

**Comment by singerdmx** [comment]
Also please don't use data as key

**Comment by singerdmx** [comment]
Table is just another embed

**Comment by singerdmx** [comment]
You should consult chatGpt how to define according to quilljs and delta

**Comment by singerdmx** [comment]
Make sure adding this to example/assets/sample_data.json to reflect it

**Comment by Abbas1Hussein** [comment]
Your insights have been incredibly helpful in guiding the development process, and I truly appreciate your dedication to maintaining the package's standards and integrity.

After carefully reviewing your feedback and considering the points you raised, I am fully committed to ensuring that the modifications align seamlessly with the existing Delta format and the schema defined by Quill. I understand the importance of adhering to established conventions and am eager to find a solution that meets both the package's requirements and the enhancements I envisioned.

I will take your suggestions into account and explore alternative approaches to incorporate the new features while maintaining consistency with the Delta format. I am dedicated to addressing the concerns you highlighted, especially regarding the usage of attributes, keys, and the overall structure of the changes.

Additionally, I will continue to consult the Quill.js documentation and seek further guidance to ensure that the final implementation not only provides the desired functionality but also integrates smoothly with the package's ecosystem.

Your feedback and expertise are immensely valuable to me, and I am committed to delivering changes that align with your vision for the `flutter_quill` package. I will keep you updated on the progress and look forward to sharing a revised proposal that addresses your concerns.

Thank you once again for your time, patience, and guidance. Your support is truly appreciated, and I am excited to work collaboratively to enhance the `flutter_quill` package for the benefit of its users.

**Comment by singerdmx** [comment]
Table is not attribute at all. 
It is another kind of Embed

**Comment by Abbas1Hussein** [comment]
> Table is not attribute at all. It is another kind of Embed

I now understand that the table is not an attribute but rather another form of embed within the Delta structure. Your explanation has provided me with a clearer perspective on how tables should be integrated into the package.

With this newfound understanding, I will reevaluate and adjust my proposed changes to ensure that the table implementation aligns correctly with the Delta format and fits seamlessly within the `flutter_quill` package's existing architecture. I apologize for any previous confusion and appreciate your patience as I work to refine my approach.

Once I have made the necessary revisions, I will provide you with an updated proposal that accurately reflects these insights and aligns with the principles of the package.

**Comment by singerdmx** [comment]
I think you should add table here https://github.com/singerdmx/flutter-quill/blob/master/flutter_quill_extensions/lib/embeds/embed_types.dart

@Jon-Salmon what do yo think?

**Comment by singerdmx** [comment]
It is embed but not exactly media type

**Comment by singerdmx** [comment]
If we add "Table", we probably should rename `QuillMediaType` to `EmbedType`

**Comment by singerdmx** [comment]
You probably want to define your proposal first in https://github.com/singerdmx/flutter-quill/blob/master/example/assets/sample_data.json

I would imagine it is similar to https://github.com/singerdmx/flutter-quill/blob/master/example/assets/sample_data.json#L4

**Comment by Abbas1Hussein** [comment]
> It is embed but not exactly media type

I wanted to take a moment to provide some context and insights into my decision to create the `flutter_quill_exc_lite` package as an alternative to the `flutter_quill_exc` package.

When I embarked on the journey of creating `flutter_quill_exc_lite`, it was driven by a series of challenges and compatibility issues that I encountered with the original package. These issues prompted me to explore solutions that would not only address the existing problems but also provide a more streamlined and optimized experience for users.

Developing a package like `flutter_quill_exc_lite` is not a simple task; it requires careful consideration, thoughtful design, and a deep understanding of the underlying framework. My intention in creating this alternative was to harness my experience and expertise to overcome the challenges I faced with the original package.

As with any software development project, there are intricacies and complexities that can only be fully understood through hands-on experience. My decision to create a separate package was driven by a commitment to ensuring a smoother user experience and compatibility across various scenarios.

I want to assure you that my goal is to enhance the capabilities of the `flutter_quill` ecosystem, and I hold your feedback and guidance in high regard. The decision to create `flutter_quill_exc_lite` was made with the utmost respect for the original package and its objectives.

I am committed to working closely with you to ensure that the changes and enhancements align with the vision of the `flutter_quill` project. Your insights and expertise are invaluable, and I am eager to collaborate on finding the best path forward.

Thank you for your understanding and support. I look forward to your continued guidance and feedback as we navigate the development of these packages.

**Comment by Abbas1Hussein** [comment]
> You probably want to define your proposal first in https://github.com/singerdmx/flutter-quill/blob/master/example/assets/sample_data.json
> 
> I would imagine it is similar to https://github.com/singerdmx/flutter-quill/blob/master/example/assets/sample_data.json#L4

I genuinely value your expertise and insights, and I am committed to working closely with you to ensure that the proposal aligns with the vision of the `flutter_quill` project. Your guidance has been instrumental in shaping the development process, and I am eager to receive your feedback on the proposed changes outlined in the `sample_data.json` file.

**Comment by freshtechtips** [comment]
Hi @Abbas1Hussein, Do you still want to merge this pull request or do any updates?? please let me know if you can.

Thank you for your patience.

**Comment by freshtechtips** [comment]
> Subject: Feature Proposal: Support for flutter_quill_extensions_lite
> 
> Hi there,
> 
> I hope this message finds you well. I have developed an additional package called `flutter_quill_extensions_lite`, which enhances the functionality of the `flutter_quill` package by providing extra features. To make this package work seamlessly, a few changes are required in the `flutter_quill` codebase.
> 
> I have made the necessary modifications to enable compatibility with `flutter_quill_extensions_lite`. These changes are essential for the successful deployment and utilization of the new package.
> 
> You can find the new package repository here: [flutter_quill_extensions_lite](https://github.com/Abbas1Hussein/flutter_quill_extensions_lite). It would be fantastic if these changes could be reviewed and merged into the `flutter_quill` repository.
> 
> Thank you for your time and consideration. I'm looking forward to your feedback.
> 
> Best regards, [Abbas Hussein]

This issue has been closed because it stays for long, feel free to open a new pull request at any time or tell us if you want to reopen

**Pull request closed without merging**
