### PR TITLE
Disable code line number in code block by default

### PR DESCRIPTION
**Pull request by freshtechtips**
Add a configuration class for the blocks in the editor

one of them is the code block and in there you will find enableLineNumbers and it's by default false

This solution thanks to @Alspb in his/her pull request [#1470](https://github.com/singerdmx/flutter-quill/pull/1470)

### CODE REVIEW

**Comment by freshtechtips** [comment]
@singerdmx 
Can everything be considered a block?? because I'm adding a class configuration which will be called block options and inside it, we will find things like code block options and in there we will configure things

like enable line numbers

if the answer is yes then feel free to merge this pull request

**Comment by singerdmx** [comment]
For the least, block vs inline means block at least occupy one line conceptually

**Comment by singerdmx** [comment]
is this change ready to merge

**Comment by freshtechtips** [comment]
> For the least, block vs inline means block at least occupy one line conceptually

So the items like custom embed builders, images, code block, checkbox etc..
can be considered as a block??

**Comment by singerdmx** [comment]
why is checkbox a block?

**Comment by singerdmx** [comment]
block is supposed to consist multiple lines (at least one)

**Comment by freshtechtips** [comment]
> why is checkbox a block?

You are right this is not the name. give me a name that represent the items like images, checkbox, code block etc..

**Comment by singerdmx** [comment]
Have you checked this https://www.youtube.com/watch?v=r502AfCX-Hw&t=284s ?

**Comment by singerdmx** [comment]
I would ask chatgpt by describing my need. It is better with names

**Comment by singerdmx** [comment]
I don't think checkbox should be treated the same way as block

**Comment by freshtechtips** [comment]
> I would ask chatgpt by describing my need. It is better with names

it's blocked in my area so I can't use it, please use it instead and told him about this to get the perfect name

**Comment by freshtechtips** [comment]
> I don't think checkbox should be treated the same way as block

Since we don't have the perfect name then should we call it something like
item, widget, view, or anything else??

**Comment by singerdmx** [comment]
I am confused why is checkbox on the table?

**Comment by freshtechtips** [comment]
> I am confused why is checkbox on the table?

I want to add a class configurations for views like checkbox, code block

to customize their behavior
for example, should we enable the line numbers in the code block??
should the checkbox have animations??

I want to follow the same approach for all the refactored code

Example of what it will be:
First the QuillEditorConfigurations
then

QuillEditorViewsConfigurations (or whatever that is called, this is why I'm asking)

- QuillEditorCheckboxConfigurations
   - animationEnabled

- QuillEditorCodeBlockConfigurations
  - enableLineNumbers

and so on

**Comment by singerdmx** [comment]
If you're simply looking for a generic and versatile name to represent items like images, checkboxes, code blocks, etc., you can use "Widget" or "Element." These terms are broad and do not imply a specific type, making them suitable for a variety of components in your application.

**Comment by singerdmx** [comment]
here are a few more generic terms you can consider:

Component
Module
Unit
Object
Item
Entity
Part
Element
Block
View

**Comment by freshtechtips** [comment]
> If you're simply looking for a generic and versatile name to represent items like images, checkboxes, code blocks, etc., you can use "Widget" or "Element." These terms are broad and do not imply a specific type, making them suitable for a variety of components in your application.

Thanks, let me commit one final change, and let's merge this...

**Comment by singerdmx** [comment]
if you're looking for terms more specific to the field of UI and design, you can consider:

UI Element
User Interface Object
Interface Component
UI Block
Display Object
User Control
Interface Item
Visual Component
Screen Element
User Interface Entity
These terms emphasize their connection to the user interface, making them more suitable for UI components in your application.

**Comment by freshtechtips** [comment]
> if you're looking for terms more specific to the field of UI and design, you can consider:
> 
> UI Element User Interface Object Interface Component UI Block Display Object User Control Interface Item Visual Component Screen Element User Interface Entity These terms emphasize their connection to the user interface, making them more suitable for UI components in your application.

I think we are ready now to merge this

**Pull request merged**
