### PR TITLE
update colorpicker to prevent error xcode build

### PR DESCRIPTION
**Pull request by raihaniyai**
Updating package `flutter_colorpicker` to prevent error which explained on issue #311

### CODE REVIEW

**Comment by singerdmx** [comment]
Could you show `flutter doc` output of your environment?

**Comment by raihaniyai** [comment]
command: flutter doctor
`[✓] Flutter (Channel dev, 2.5.0-1.0.pre, on macOS 11.4 20F71 darwin-x64, locale en-ID)
    • Flutter version 2.5.0-1.0.pre at /Users/raihaniyai/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 184e5871be (7 days ago), 2021-07-26 04:38:02 -0400
    • Engine revision a877f6fed6
    • Dart version 2.14.0 (build 2.14.0-350.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] VS Code (version 1.47.3)
    • VS Code at /Users/raihaniyai/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • E0B7E646-C0E1-4544-AB91-004EAFCAED4A • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google
      Chrome 92.0.4515.107

! Doctor found issues in 1 category.`

**Comment by singerdmx** [comment]
You are on dev channel
We are on stable channel

**Comment by raihaniyai** [comment]
`flutter doctor`
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-ID)
    • Flutter version 2.2.3 at /Users/raihaniyai/Developer/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/raihaniyai/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] VS Code (version 1.47.3)
    • VS Code at /Users/raihaniyai/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107

! Doctor found issues in 1 category.

**Comment by singerdmx** [comment]
I am using Channel stable, 2.2.3 and I don't have this issue

**Comment by singerdmx** [comment]
https://flutter.dev/docs/release/breaking-changes/gesture-recognizer-add-allowed-pointer


image

**Comment by singerdmx** [comment]
image

**Comment by mgyarmathy** [comment]
@singerdmx This breaking change landed in stable (2.5.0) today (https://flutter.dev/docs/release/breaking-changes/gesture-recognizer-add-allowed-pointer). Might be time to revisit this PR.

**Pull request merged**
