### PR TITLE
Bug fixes and new callback

### PR DESCRIPTION
**Pull request by freshtechtips**
Fix bugs:

1. [#1481](https://github.com/singerdmx/flutter-quill/issues/1481)
2. [#1484](https://github.com/singerdmx/flutter-quill/issues/1484)

and add a new callback

### CODE REVIEW

**Comment by singerdmx** [comment]
I won't be able to publish until 7 hours later

**Comment by freshtechtips** [comment]
> I won't be able to publish until 7 hours later 

I don't mind it doesn't make much difference to me

But you don't have to publish yet

Let's fix other things and add more stuff

It's up to you.

**Comment by singerdmx** [comment]
I will confirm with you before I publish

**Comment by singerdmx** [comment]
I am ready to publish 
Do you want me to go ahead?

**Pull request merged**
