### PR TITLE
Changes to default editor and toolbar values

### PR DESCRIPTION
**Pull request by milindgoel15**
- Added an option to define a custom text selection colour in the editor
- Added an option to set up box decoration for the toolbar.

### CODE REVIEW

**Comment by freshtechtips** [comment]
Good work.

The box decoration change is good and it's useful but the color selection is not needed because I already did it and we will not have a conflict because I did it by overriding the textSelectionThemeData and not just the cursor color

and the approach I use will allow further customization

**Comment by milindgoel15** [comment]
> the color selection is not needed because I already did it and we will not have a conflict because I did it by overriding the textSelectionThemeData and not just the cursor color

In such case, the toolbar commit can be cherry-picked.

**Comment by singerdmx** [comment]
Let me know if this PR should be closed

**Comment by milindgoel15** [comment]
You can cherry pick the commit related to toolbar.

**Comment by freshtechtips** [comment]
> You can cherry pick the commit related to toolbar.

Just remove everything that is related to 
`Added an option to define a custom text selection color in the editor` feature and try to solve the conflicts, I don't have write access you might want to ask @singerdmx to solve the conflicts for you if needed

**Comment by freshtechtips** [comment]
> You can cherry pick the commit related to toolbar.

There is another option, which I take the changes yours and send it in the next pull request, please let me know how would you like to solve it

by the changes, I mean the box decoration and not the others

**Comment by freshtechtips** [comment]
> I will publish but @Jon-Salmon owns the package of extension

Only flutter_quill needed to be updated

**Comment by freshtechtips** [comment]
> Reverted the commit related to text selection. PR can be merged now

Hi again, can you share your opinion on [this](https://github.com/singerdmx/flutter-quill/discussions/1441) ??
Are you okay with the changes as a developer who will use that library or a maintainer??

**Pull request merged**
