### PR TITLE
Flutter 3.13.0 compability fix

### PR DESCRIPTION
**Pull request by VladimirKaroyan**

### CODE REVIEW

**Comment by singerdmx** [comment]
is Flutter 3.13.0 released on stable?

**Comment by singerdmx** [comment]
```
Run flutter analyze
Analyzing flutter-quill...                                      

   info • The member 'liveTextInputEnabled' overrides an inherited member but isn't annotated with '@override' • lib/src/widgets/editor.dart:45:12 • annotate_overrides
   info • The variable 'customButton' should be final • lib/src/widgets/toolbar.dart:5[7](https://github.com/singerdmx/flutter-quill/actions/runs/5882432848/job/15953111742?pr=1361#step:7:8)7:1[8](https://github.com/singerdmx/flutter-quill/actions/runs/5882432848/job/15953111742?pr=1361#step:7:9) • prefer_final_in_for_each
   info • The variable 'fontFamily' should be final • lib/src/widgets/toolbar/quill_font_family_button.dart:167:3[9](https://github.com/singerdmx/flutter-quill/actions/runs/5882432848/job/15953111742?pr=1361#step:7:10) • prefer_final_in_for_each
   info • The variable 'fontSize' should be final • lib/src/widgets/toolbar/quill_font_size_button.dart:154:39 • prefer_final_in_for_each
```

**Comment by singerdmx** [comment]
Can you address the `flutter analyze failure`

**Comment by VladimirKaroyan** [comment]
@singerdmx Flutter analyze issues fixed, also code reformat has been done.

**Comment by VladimirKaroyan** [comment]
Also it's currently blocker for us, we are trying to release our app with the flutter upgraded version and it brakes on run because of compability issues)

**Comment by VladimirKaroyan** [comment]
@singerdmx Thanks for merging and releasing, already upgraded, everything works pretty well now 😎

**Pull request merged**
