### PR TITLE
Fixes toolbar buttons stealing focus from editor.

### PR DESCRIPTION
**Pull request by Blquinn**
ISSUE: [955](https://github.com/singerdmx/flutter-quill/issues/955)

I think another decent option would be to simply pass the FocusNode to the buttons instead of having this callback.

### CODE REVIEW

**Review by singerdmx — CHANGES_REQUESTED** [review]
Update gitignore for vscode

**Comment by Blquinn** [comment]
I was fixing the gitignore... Did you mean to merge that?

**Comment by singerdmx** [comment]
It is fine

**Comment by Blquinn** [comment]
Ok :+1:

**Pull request merged**
