### PR TITLE
Fix certain keys not working on web when editor is in a scroll view (#304)

### PR DESCRIPTION
**Pull request by NicolasDionB**
Implements the fix proposed by @wliumelb from issue #304

### CODE REVIEW

**Comment by galenwarren** [comment]
@NicolasDionB Doesn't the FocusNode introduced here need to be disposed?

**Comment by NicolasDionB** [comment]
@galenwarren You may be right. Anyway a disposal could be good. If you could provide a PR that would be great!

**Comment by galenwarren** [comment]
Thanks @NicolasDionB

I came across this trying to get keyboard-focus tab order to work cleanly in Flutter web with the QuillEditor control. There were two issues wrt this code:

```
      return KeyboardListener(
        onKeyEvent: (_) {},
        focusNode: FocusNode(
          onKeyEvent: (node, event) => KeyEventResult.skipRemainingHandlers,
        ),
        child: editor,
      );
```

- The FocusNode's not being reused and disposed was causing the focus tree to get corrupted on rebuild such that I couldn't tab into the control at all
- Its using the default value (true) for `canRequestFocus` was causing it to take focus when using tab, so it would take two presses of the tab key to get into the text content, instead of just one.

Creating it like so:

```
  final _keyboardListenerFocusNode = FocusNode(
    canRequestFocus: false,
    onKeyEvent: (node, event) => KeyEventResult.skipRemainingHandlers,
  );
```

... and then disposing it seems to fix those issues. This is what I'd include in the PR.

However, there's another thing I wanted to ask you about. In my case, I'd like to capture the tab key in the QuillEditor control and have it move to the next field on my form. As far as I can tell, there is no way to do that, because in the lowest level of the control it captures key events and always translates tab to some sort of content. I don't see any way to prevent this behavior or otherwise hook it.

What would you think of about my adding an `onKeyEvent` property to, say, `QuillEditorConfigurations`, to allow the user to specify a key handler that would get applied before applying the built-in handlers for tab, space, etc? It could have the same signature as the one on FocusNode. Or do you have a better idea for how I might capture the tab key and prevent the default behavior in the control?

**Comment by galenwarren** [comment]
@NicolasDionB Wondering if you have any thoughts on the proposal to add an ```onKeyEvent``` handler to allow callers to override handling for particular keys? I can include that in the PR as well, if you're on board.

**Comment by NicolasDionB** [comment]
@galenwarren Personally I like the idea but you should create a different PR for that, more specific to that addition. Also keep in mind that I'm not a senior on this project, just a casual user/contributor 😊

**Pull request merged**
