### PR TITLE
Update some dependencies

### PR DESCRIPTION
**Pull request by mark8044**
Update some dependencies, notable i18n_extension which conflicts with intl updates

### CODE REVIEW

**Comment by singerdmx** [comment]
Please update changelog

**Comment by mark8044** [comment]
> Please update changelog

Ok I just did it

**Comment by adil192** [comment]
I think we might need to revert `i18n_extension: ^7.0.0` because it depends on `intl: ^0.18.0` which most packages don't support.

Even in the example app, `flutter pub get` fails unless `intl: ^0.18.0` is added to `dependency_overrides` (which we ideally shouldn't have in a production app). As a temporary hack, I've done this in this commit: https://github.com/adil192/flutter-quill/commit/697759f34c8fcaa7b292925684b5e0b955bc60d9.

I also have to use `dependency_overrides` for `intl` in my app Saber, following https://github.com/provokateurin/nextcloud-neon/issues/195. This is because flutter_localizations (from the flutter sdk) depends on `intl: ^0.17.0`.

I propose that we set `i18n_extension` back to `^6.0.0`, and anyone who absolutely needs to use `^7.0.0` can use something like this in their app's pubspec since `i18n_extension` is less used than `intl`:
```yaml
dependency_overrides:
  i18n_extension: ^7.0.0
  intl: ^0.18.0
```

**Comment by mark8044** [comment]
@adil192 @singerdmx You should actually go UP to `i18n_extension 8.0.0` as that is using `intl: ^0.17.0`

**Comment by adil192** [comment]
I'll make another pull request, thanks for letting us know

**Comment by mark8044** [comment]
@adil192 already there :)

**Pull request merged**
