### PR TITLE
Fixes for previous step

### PR DESCRIPTION
**Pull request by freshtechtips**
Important changes for previous steps
this update should be published as it is required for fresh_quill_extensions which will be a temp alternative to flutter_quill_extensions

Also, it's updated some of the old documentation in readme

### CODE REVIEW

**Comment by singerdmx** [comment]
FYI I won't be able to publish it until 7 hours later

**Comment by freshtechtips** [comment]
> FYI I won't be able to publish it until 7 hours later

This is up to you but why not?

**Comment by singerdmx** [comment]
Because I don't have my computer

**Comment by freshtechtips** [comment]
> Because I don't have my computer

Sound tough, then I will work on the new package more by refactoring things
The latest versions of Flutter have more warnings than the one we are using in flutter_quill and flutter_quill_extensions

**Comment by mtallenca** [comment]
I'm using this commit and have a custom tool bar with the following code...

```
quill.QuillToolbarProvider(
                toolbarConfigurations: quill.QuillToolbarConfigurations(
                  toolbarSize: toolbarIconSize * 2,
                  multiRowsDisplay: false,
                ),
                child: quill.QuillBaseToolbar(
                  configurations: quill.QuillBaseToolbarConfigurations(
                    toolbarSize: toolbarIconSize * 2,
                    multiRowsDisplay: false,
                    childrenBuilder: (context) {
```
                    
 w/o a QuillToolbarProvider - there is an exception....  So I need a Provider, however, the same settings are in the QuillBaseToolbarConfigurations.  Do I need the same settings ?

**Comment by freshtechtips** [comment]
> QuillToolbarProvider

The QuillToolbarProvider is responsible for providing the toolbar the configurations instance it needs for it children internally
The QuillProvider define the shared settings between both toolbar and the editor

**Comment by freshtechtips** [comment]
> I'm using this commit and have a custom tool bar with the following code...
> 
> ```
> quill.QuillToolbarProvider(
>                 toolbarConfigurations: quill.QuillToolbarConfigurations(
>                   toolbarSize: toolbarIconSize * 2,
>                   multiRowsDisplay: false,
>                 ),
>                 child: quill.QuillBaseToolbar(
>                   configurations: quill.QuillBaseToolbarConfigurations(
>                     toolbarSize: toolbarIconSize * 2,
>                     multiRowsDisplay: false,
>                     childrenBuilder: (context) {
> ```
> 
> w/o a QuillToolbarProvider - there is an exception.... So I need a Provider, however, the same settings are in the QuillBaseToolbarConfigurations. Do I need the same settings ?

Example of how it will look like from the end developer perspective:

```dart
QuillProvider(
          configurations: QuillConfigurations(
            controller: _controller,
            sharedConfigurations: const QuillSharedConfigurations(
              locale: Locale('de'),
            ),
          ),
          child: Column(
            children: [
              const QuillToolbar(),
              Expanded(
                child: QuillEditor.basic(
                  configurations: const QuillEditorConfigurations(
                    readOnly: false,
                  ),
                ),
              )
            ],
          ),
        )
```

For creating a custom toolbar with this library support You need to use QuillBaseToolbar and it uses a provider for the QuillToolbarProvider internally so no need for creating a second provider, just the quill provider for shared configurations

**Comment by freshtechtips** [comment]
> I'm using this commit and have a custom tool bar with the following code...
> 
> ```
> quill.QuillToolbarProvider(
>                 toolbarConfigurations: quill.QuillToolbarConfigurations(
>                   toolbarSize: toolbarIconSize * 2,
>                   multiRowsDisplay: false,
>                 ),
>                 child: quill.QuillBaseToolbar(
>                   configurations: quill.QuillBaseToolbarConfigurations(
>                     toolbarSize: toolbarIconSize * 2,
>                     multiRowsDisplay: false,
>                     childrenBuilder: (context) {
> ```
>                     
>  w/o a QuillToolbarProvider - there is an exception....  So I need a Provider, however, the same settings are in the QuillBaseToolbarConfigurations.  Do I need the same settings ?

If you are still facing the issue or any others, please let me know

**Comment by mtallenca** [comment]
QuillBaseToolbar throws an exception if no provider is defined above it.

**Comment by freshtechtips** [comment]
> QuillBaseToolbar throws an exception if no provider is defined above it.

Do you mean QuillProvider or QuillToolbarProvider?? it only needs QuillProvider

**Comment by mtallenca** [comment]
QuillToolbarProvider.  When it's not provided QuillBaseToolbar throws an exception.

**Comment by freshtechtips** [comment]
> QuillToolbarProvider. When it's not provided QuillBaseToolbar throws an exception.

Hi. Can you send me the code snippets to encounter the issue??

**Comment by freshtechtips** [comment]
> QuillToolbarProvider. When it's not provided QuillBaseToolbar throws an exception.

Because if you are using QuillToolbar or QuillBaseToolbar it already defined internally for you, you don't have to wrap your widget with it

**Comment by mtallenca** [comment]
I have the following code that works:

`      return quill.QuillProvider(
        configurations: quill.QuillConfigurations(
          controller: _controller!,
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            if (titleWidget != null) titleWidget,
            Expanded(
              child: TecAutoScroll(
                allowAutoscroll: () {
                  return !_editMode;
                },
                autoscrollActive: (active) {
                  if (active) {
                    _autoScrolling = active;
                  } else {
                    Future.delayed(const Duration(milliseconds: 250), () {
                      _autoScrolling = false;
                    });
                  }
                },
                scrollController: _scrollController,
                navigationBarPadding: () => context.fullBottomBarPadding,
                contentTextScaleFactor: contentTextScaleFactorWith(context),
                child: TecScrollbar(
                  controller: _scrollController,
                  child: MediaQuery(
                    data: MediaQuery.of(context)
                        .copyWith(textScaleFactor: contentTextScaleFactorWith(context)),
                    child: BlocBuilder<ContentSettingsBloc, ContentSettings>(
                        builder: (context, settings) {
                      return DefaultTextStyle(
                        style: textStyleWith(settings.fontName,
                            color: Theme.of(context).textColor ?? Colors.black),
                        child: _largeDocument
                            ? Padding(
                                padding: EdgeInsets.only(
                                    top: quillTopPadding, left: 15, bottom: 0, right: 15),
                                child: SingleChildScrollView(
                                  controller: _scrollController,
                                  child: SelectableText(
                                    _note.info,
                                    maxLines: null,
                                  ),
                                ),
                              )
                            : quill.QuillEditor(
                                key: _editorKey,
                                scrollController: _scrollController,
                                focusNode: _focusNode,
                                configurations: quill.QuillEditorConfigurations(
                                  scrollable: true,
                                  autoFocus: _editMode,
                                  showCursor: _editMode,
                                  readOnly: !_editMode,
                                  enableUnfocusOnTapOutside: false,
                                  keyboardAppearance: Theme.of(context).brightness,
                                  onLaunchUrl: _onLaunchUrl,
                                  linkActionPickerDelegate: _linkActionPickerDelegate,
                                  expands: true,
                                  padding: EdgeInsets.only(
                                      top: quillTopPadding, left: 15, bottom: 200, right: 15),
                                ),
                              ),
                      );
                    }),
                  ),
                ),
              ),
            ),
            if (_editMode && _showToolbar) ...[
              quill.QuillToolbarProvider(
                toolbarConfigurations: quill.QuillToolbarConfigurations(
                  toolbarSize: toolbarIconSize * 2,
                  multiRowsDisplay: false,
                ),
                child: quill.QuillBaseToolbar(
                  configurations: quill.QuillBaseToolbarConfigurations(
                    toolbarSize: toolbarIconSize * 2,
                    multiRowsDisplay: false,
                    childrenBuilder: (context) {
                      final controller =
                          quill.QuillProvider.ofNotNull(context).configurations.controller;
                      return [
                        quill.QuillToolbarHistoryButton(
                          controller: controller,
                          options: const quill.QuillToolbarHistoryButtonOptions(isUndo: true),
                        ),
                        quill.QuillToolbarHistoryButton(
                          controller: controller,
                          options: const quill.QuillToolbarHistoryButtonOptions(isUndo: false),
                        ),
                        quill.QuillToolbarToggleStyleButton(
                          attribute: quill.Attribute.bold,
                          controller: controller,
                          options: quill.QuillToolbarToggleStyleButtonOptions(
                            iconData: Icons.format_bold,
                            iconSize: toolbarIconSize,
                          ),
                        ),
                        quill.QuillToolbarToggleStyleButton(
                          attribute: quill.Attribute.italic,
                          controller: controller,
                          options: quill.QuillToolbarToggleStyleButtonOptions(
                            iconData: Icons.format_italic,
                            iconSize: toolbarIconSize,
                          ),
                        ),
                        quill.QuillToolbarToggleStyleButton(
                          attribute: quill.Attribute.underline,
                          controller: controller,
                          options: quill.QuillToolbarToggleStyleButtonOptions(
                            iconData: Icons.format_underline,
                            iconSize: toolbarIconSize,
                          ),
                        ),
                        quill.QuillToolbarClearFormatButton(
                          controller: controller,
                          options: quill.QuillToolbarClearFormatButtonOptions(
                            iconData: Icons.format_clear,
                            iconSize: toolbarIconSize,
                          ),
                        ),
                        if (widget.note.type == UserItemType.note.index)
                          PasteButton(
                            icon: AppIcons.selectionPaste,
                            iconSize: toolbarIconSize,
                            controller: controller,
                            undo: true,
                          ),
                        VerticalDivider(
                          indent: 12,
                          endIndent: 12,
                          color: Colors.grey.shade400,
                        ),
                        quill.QuillToolbarSelectHeaderStyleButtons(
                          controller: controller,
                          options: quill.QuillToolbarSelectHeaderStyleButtonsOptions(
                            iconSize: toolbarIconSize,
                          ),
                        ),
                        quill.QuillToolbarToggleStyleButton(
                          attribute: quill.Attribute.ol,
                          controller: controller,
                          options: quill.QuillToolbarToggleStyleButtonOptions(
                            iconData: Icons.format_list_numbered,
                            iconSize: toolbarIconSize,
                          ),
                        ),
                        quill.QuillToolbarToggleStyleButton(
                          attribute: quill.Attribute.ul,
                          controller: controller,
                          options: quill.QuillToolbarToggleStyleButtonOptions(
                            iconData: Icons.format_list_bulleted,
                            iconSize: toolbarIconSize,
                          ),
                        ),
                        quill.QuillToolbarToggleStyleButton(
                          attribute: quill.Attribute.blockQuote,
                          controller: controller,
                          options: quill.QuillToolbarToggleStyleButtonOptions(
                            iconData: Icons.format_quote,
                            iconSize: toolbarIconSize,
                          ),
                        ),
                        VerticalDivider(
                          indent: 12,
                          endIndent: 12,
                          color: Colors.grey.shade400,
                        ),
                        quill.QuillToolbarIndentButton(
                            controller: controller,
                            isIncrease: true,
                            options: quill.QuillToolbarIndentButtonOptions(
                              iconData: Icons.format_indent_increase,
                              iconSize: toolbarIconSize,
                            )),
                        quill.QuillToolbarIndentButton(
                          controller: controller,
                          isIncrease: false,
                          options: quill.QuillToolbarIndentButtonOptions(
                            iconData: Icons.format_indent_decrease,
                            iconSize: toolbarIconSize,
                          ),
                        ),
                      ];
                    },
                  ),
                ),
              ),
              BlocBuilder<SheetManagerBloc, SheetManagerState>(builder: (context, sheetState) {
                return SizedBox(height: sheetState.selectionSheetHeight);
              }),
            ],
          ],
        ),
      );`

**Comment by freshtechtips** [comment]
> [QuillToolbarProvider_Exception.zip](https://github.com/singerdmx/flutter-quill/files/13126771/QuillToolbarProvider_Exception.zip)
> 
> working code / exception code w/diff, exception and stack trace of exception

Thank you for the report once again, I will checkout soon

**Comment by freshtechtips** [comment]
> [QuillToolbarProvider_Exception.zip](https://github.com/singerdmx/flutter-quill/files/13126771/QuillToolbarProvider_Exception.zip)
> 
> working code / exception code w/diff, exception and stack trace of exception

I'm able to encounter the issue, give us some time to debug it and we will see what we can do to fix this issue

**Comment by freshtechtips** [comment]
> [QuillToolbarProvider_Exception.zip](https://github.com/singerdmx/flutter-quill/files/13126771/QuillToolbarProvider_Exception.zip)
> 
> working code / exception code w/diff, exception and stack trace of exception

Issue fixed, it require a little adjusments from the library side but there is another issue

you are using the buttons of the `QuillToolbar` outside of it, the buttons need the `QuillToolbarProvider above of them

it should look something like this

```dart

  QuillToolbarProvider(
                toolbarConfigurations: const QuillToolbarConfigurations(),
                child: QuillBaseToolbar(
                  configurations: QuillBaseToolbarConfigurations(
                    toolbarSize: 15 * 2,
                    multiRowsDisplay: false,
                    childrenBuilder: (context) {
                      final controller = context.requireQuillController;
                      return [
                        QuillToolbarHistoryButton(
                          controller: controller,
                          options: const QuillToolbarHistoryButtonOptions(
                              isUndo: true),
                        ),
                        QuillToolbarHistoryButton(
                          controller: controller,
                          options: const QuillToolbarHistoryButtonOptions(
                              isUndo: false),
                        ),
                        QuillToolbarToggleStyleButton(
                          attribute: Attribute.bold,
                          controller: controller,
                          options: const QuillToolbarToggleStyleButtonOptions(
                            iconData: Icons.format_bold,
                            iconSize: 20,
                          ),
                        ),
                        QuillToolbarToggleStyleButton(
                          attribute: Attribute.italic,
                          controller: controller,
                          options: const QuillToolbarToggleStyleButtonOptions(
                            iconData: Icons.format_italic,
                            iconSize: 20,
                          ),
                        ),
                        QuillToolbarToggleStyleButton(
                          attribute: Attribute.underline,
                          controller: controller,
                          options: const QuillToolbarToggleStyleButtonOptions(
                            iconData: Icons.format_underline,
                            iconSize: 20,
                          ),
                        ),
                        QuillToolbarClearFormatButton(
                          controller: controller,
                          options: const QuillToolbarClearFormatButtonOptions(
                            iconData: Icons.format_clear,
                            iconSize: 20,
                          ),
                        ),
                        // if (widget.note.type == UserItemType.note.index)
                        //   PasteButton(
                        //     icon: AppIcons.selectionPaste,
                        //     iconSize: toolbarIconSize,
                        //     controller: controller,
                        //     undo: true,
                        //   ),
                        VerticalDivider(
                          indent: 12,
                          endIndent: 12,
                          color: Colors.grey.shade400,
                        ),
                        QuillToolbarSelectHeaderStyleButtons(
                          controller: controller,
                          options:
                              const QuillToolbarSelectHeaderStyleButtonsOptions(
                            iconSize: 20,
                          ),
                        ),
                        QuillToolbarToggleStyleButton(
                          attribute: Attribute.ol,
                          controller: controller,
                          options: const QuillToolbarToggleStyleButtonOptions(
                            iconData: Icons.format_list_numbered,
                            iconSize: 20,
                          ),
                        ),
                        QuillToolbarToggleStyleButton(
                          attribute: Attribute.ul,
                          controller: controller,
                          options: const QuillToolbarToggleStyleButtonOptions(
                            iconData: Icons.format_list_bulleted,
                            iconSize: 20,
                          ),
                        ),
                        QuillToolbarToggleStyleButton(
                          attribute: Attribute.blockQuote,
                          controller: controller,
                          options: const QuillToolbarToggleStyleButtonOptions(
                            iconData: Icons.format_quote,
                            iconSize: 20,
                          ),
                        ),
                        VerticalDivider(
                          indent: 12,
                          endIndent: 12,
                          color: Colors.grey.shade400,
                        ),
                        QuillToolbarIndentButton(
                            controller: controller,
                            isIncrease: true,
                            options: const QuillToolbarIndentButtonOptions(
                              iconData: Icons.format_indent_increase,
                              iconSize: 20,
                            )),
                        QuillToolbarIndentButton(
                          controller: controller,
                          isIncrease: false,
                          options: const QuillToolbarIndentButtonOptions(
                            iconData: Icons.format_indent_decrease,
                            iconSize: 20,
                          ),
                        ),
                      ];
                    },
                  ),
                ),
              ),

```

**Comment by freshtechtips** [comment]
> [QuillToolbarProvider_Exception.zip](https://github.com/singerdmx/flutter-quill/files/13126771/QuillToolbarProvider_Exception.zip)
> 
> working code / exception code w/diff, exception and stack trace of exception

Also the extension functions for BuildContext is now public after this pull request so you can use


```dart
final controller = context.requireQuillController;
```

for a little bit better syntax, shorter and cleaner

**Comment by freshtechtips** [comment]
> [QuillToolbarProvider_Exception.zip](https://github.com/singerdmx/flutter-quill/files/13126771/QuillToolbarProvider_Exception.zip)
> 
> working code / exception code w/diff, exception and stack trace of exception

Please let me know if you still facing this issue or others

**Comment by mtallenca** [comment]
Working with latest commit thx!

**Comment by freshtechtips** [comment]
> Working with latest commit thx!  

You are welcome!!

**Comment by freshtechtips** [comment]
> FYI I won't be able to publish it until 7 hours later

Hi, hope your trap ends well

if you are back now can you publish the package with this pull request?? just minor changes but it's necessary in order to work

**Comment by freshtechtips** [comment]
@singerdmx 
Hi, hope your trap ends well

if you are back now. 
Can you publish the package with this pull request?? just minor changes but it's necessary in order to work

**Comment by singerdmx** [comment]
I will publish it in 30 min

**Pull request merged**
