### PR TITLE
Fix compatibility with upcoming flutter 3.16

### LINKED ISSUE #1415: [Mobile] -- Upgrade incompatibility  issue     MAJOR ERROR
My issue is about [Mobile]

I have tried running version 5.2.11 successfully before creating an issue here. 

After upgrade latest version flutter version stable channel.  many run errors pop up..

`/C:/Users/../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-6.4.2/lib/src/widgets/text_selection.dart:716:9: Error: Type 'DragSelectionUpdateCallback' not found.
  final DragSelectionUpdateCallback? onDragSelectionUpdate;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-6.4.2/lib/src/widgets/raw_editor.dart:253:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
 - TextInputClient.insertContent
 - TextSelectionDelegate.liveTextInputEnabled
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RawEditorState extends EditorState
      ^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/text_input.dart:1124:8: Context: 'TextInputClient.insertContent' is defined here. 
  void insertContent(KeyboardInsertedContent content) {}
       ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/text_input.dart:1058:12: Context: 'TextSelectionDelegate.liveTextInputEnabled' is defined here.
  bool get liveTextInputEnabled => false;
           ^^^^^^^^^^^^^^^^^^^^
/C:/Users/../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-6.4.2/lib/src/widgets/raw_editor.dart:309:47: Error: Required named parameter 'onLiveTextInput' must be provided.
    return EditableText.getEditableButtonItems(
                                              ^
/C:/flutter/packages/flutter/lib/src/widgets/editable_text.dart:1832:38: Context: Found this candidate, but the arguments don't match.
  static List<ContextMenuButtonItem> getEditableButtonItems({
                                     ^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_quill-6.4.2/lib/src/widgets/text_selection.dart:716:9: Error: 'DragSelectionUpdateCallback' isn't a type.
  final DragSelectionUpdateCallback? onDragSelectionUpdate;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^`
**### Please help**

### PR DESCRIPTION
**Pull request by FaFre**
# Pull Request

## Description

Adapt new overrides introduced in the beta branch of flutter.

## Issues

Closes #1415 

## Additional notes
I add this as a draft because this seem to be a breaking change in the flutter framework and is probably not backward compatible.

There are still warnings about deprecated `TextScaleFactor` which haven't been fixed yet.

## Checklist

- [ x] I have added/updated relevant documentation 
- [ x] I have tested these changes locally. 
- [ x] I have followed the code style and guidelines. 
- [ ] I have updated `CHANGELOG.md` with my changes in the next section 
- [x ] I have run `dart format .`` on the project 
- [ x] I have run `dart fix --apply` on the project 
- [ x] I have run `flutter test` and `flutter analyze` and it passed successfully 
- [ ] I have run `./before-push.sh` and everything is fine

### CODE REVIEW

**Comment by singerdmx** [comment]
We only support master

**Comment by freshtechtips** [comment]
> # Pull Request
> ## Description
> Adapt new overrides introduced in the beta branch of flutter.
> 
> ## Issues
> Closes #1415
> 
> ## Improvements
> ## Features
> ## Additional notes
> I add this as a draft because this seem to be a breaking change in the flutter framework and is probably not backward compatible.
> 
> There are still warnings about deprecated `TextScaleFactor` which haven't been fixed yet.
> 
> ## Suggestions
> ## Checklist
> * [ x] I have added/updated relevant documentation
> * [ x] I have tested these changes locally.
> * [ x] I have followed the code style and guidelines.
> * [ ]  I have updated `CHANGELOG.md` with my changes in the next section
> * [x ] I have run `dart format .`` on the project
> * [ x] I have run `dart fix --apply` on the project
> * [ x] I have run `flutter test` and `flutter analyze` and it passed successfully
> * [ ]  I have run `./before-push.sh` and everything is fine

Hi, thank you for your attention to such details but we will do that when the changes of the beta version get released into the stable or master channel

If you have any questions feel free to ask us on GitHub

**Comment by freshtechtips** [comment]
We will get back to your changes when the new changes got released into the stable channel

**Comment by FaFre** [comment]
> We only support master

sure, its only a draft

**Comment by freshtechtips** [comment]
> > We only support master
> 
> sure, its only a draft. Just merge it when you are ready please.

Sure

**Comment by freshtechtips** [comment]
The 3.16 just got released, and we are currently working to add the support for it

**Pull request merged**
