### PR TITLE
Mirgration Guide and update README.md

### PR DESCRIPTION
**Pull request by freshtechtips**
Just updating the documentation to be more readable, adding a migration guide, and that almost all

but the important change was changing the version number to `8.0.0`
which is something we should have done but I hope we don't make any more breaking changes because we don't want the version number to reach 100 in one month

### CODE REVIEW

**Comment by singerdmx** [comment]
I won't be able to publish it until 7 hours later

**Comment by freshtechtips** [comment]
@singerdmx Wait don't merge yet, I'm getting a warrning


```
Package validation found the following potential issue:
* Rename the top-level "docs" directory to "doc".
  The Pub layout convention is to use singular directory names.
  Plural names won't be correctly identified by Pub and other tools.
  See https://dart.dev/tools/pub/package-layout.

```

What do you say?? should we rename the folder from `docs` to `doc` to follow the pub convention??

**Comment by singerdmx** [comment]
Sure

**Comment by freshtechtips** [comment]
> I won't be able to publish it until 7 hours later



> Sure

Done, do you know how I can chat with @Jon-Salmon in private??

**Comment by singerdmx** [comment]
No idea he is probably in Europe?

**Comment by freshtechtips** [comment]
> No idea he is probably in Europe?

I mean private chat using something like Discord, Slack, Telegram etc...

**Comment by singerdmx** [comment]
No idea

**Comment by freshtechtips** [comment]
> No idea

I think this pull request is ready to merge if you are ready
sure we can't publish this yet to pub.dev bu at least the people in GitHub can see the migration guide

**Pull request merged**
