### PR TITLE
Move flutter_quill_test to seperated package

### PR DESCRIPTION
**Pull request by freshtechtips**
This pull request will be ready in a few moments

it aims to move `flutter_quill_test` library that inside `flutter_quill` to different package called `flutter_quill_test` and it also move the `flutter_test` to dev dev_dependencies

### CODE REVIEW

**Review by singerdmx — APPROVED** [review]

**Comment by freshtechtips** [comment]
That is strange, I don't get any error in my local machine

image

**Comment by singerdmx** [comment]
Did you add all files in commit?

**Comment by singerdmx** [comment]
You may have the file locally but forgot to include it in the commit

**Comment by freshtechtips** [comment]
> You may have the file locally but forgot to include it in the commit

Maybe I was in sub folder and add everything from that sub folder, I tried again from the root folder

**Comment by freshtechtips** [comment]
I think we are ready now, but to publish `flutter_quill_test` we first need to publish the new version of `flutter_quill` which contains the new export

**Comment by singerdmx** [comment]
published

**Pull request merged**
