### PR TITLE
Migrated to null safety. Moved package universal_ui to universal_ui.d…

### PR DESCRIPTION
**Pull request by jwehrle**
…art since there was no null safe version available at this time.

### CODE REVIEW

**Comment by singerdmx** [comment]
Please resolve conflicts

**Comment by singerdmx** [comment]
Please DO NOT randomly remove code!

**Comment by jwehrle** [comment]
This feedback is confusing. The only code removed in this commit were superfluous null checks. When migrating to null safety, there will be null checks to remove.

**Comment by singerdmx** [comment]
Sorry, my bad
But the code is already null safe.
Please sync to latest

**Pull request closed without merging**
