### PR TITLE
Native IOS keyboard input Chinese characters: bold ,underline ,color, italics will be invalid . how can i do it ?

### PR DESCRIPTION
**Pull request by quinoxz**
Native IOS keyboard input Chinese characters: bold ,underline ,color, italics will be invalid . how can i do it ?

### CODE REVIEW

**Comment by singerdmx** [comment]
This is way out of date

**Comment by singerdmx** [comment]
I think dev branch is not maintained.
I am going to delete dev branch

**Comment by singerdmx** [comment]
Please work on master branch instead

**Comment by quinoxz** [comment]
> 请改为在主分支上工作
I can't create PR on the main branch

**Comment by singerdmx** [comment]
Why?
You can create a commit in your forked repo. Then let me know your commit and I will pick it up.

**Pull request closed without merging**
