### PR TITLE
Refactor: Moved core link button functions to link.dart

### PR DESCRIPTION
**Pull request by Alspb**
## Description

Moved link functions used in two link buttons (`link_style_button.dart` and `link_style2_button.dart`) into `link.dart`, so

1. The users can use these functions in their custom link button dialogs,
2. `link_style_button.dart` and `link_style2_button.dart` use the same functions instead of having two independent copies of them.

## Checklist

- [x] I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the package version in `pubspec.yaml` files.
- [x] All existing and new tests are passing.
- [x] I have run the commands in `./scripts/before_push.sh` and it all passed successfully

## Breaking Change

Does your PR require developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by EchoEllet** [comment]
Thank you for the cleanup. 

Those two tests are unrelated with this PR. It might be that the tests are outdated with recent changes of `flutter_quill_delta_from_html`.

**Comment by CatHood0** [comment]
> As far as I see, these two tests fail in master too.

These are tests that I created. If you can take advantage and fix it, I will tell you that it was actually due to a change that was made in the latest version of `flutter_quill_delta_from_html`

Before, when a video was inserted in the Delta, two operations were performed, the first, where a new line was inserted, to separate the video from any text (this was eliminated since the text can be directly next to a video block), and then the video block

In both there is the same error since you need to delete a new line that will never arrive:

This is the expected `Delta` of "should detect video and parse correctly"
 
```dart
final expectedDeltaVideo = Delta.fromOperations([
 Operation.insert('\n'),
 Operation.insert({'video': 'https://www.youtube.com/embed/dQw4w9WgXcQ'}),
 Operation.insert('\n'),
 ]);
```

And with the correct format you should expect is this `Delta`:

```dart
 final expectedDeltaVideo = Delta.fromOperations([
 Operation.insert({'video': 'https://www.youtube.com/embed/dQw4w9WgXcQ'}),
 Operation.insert('\n'),
 ]);
```

This is the expected `Delta` for "should detect by different way normal link and video link":

```dart
 final expectedDeltaLinkAndVideoLink = Delta.fromOperations([
 Operation.insert('fdsfsd', {'link': 'https://www.macrumors.com/'}),
 Operation.insert('\n\n'),
 Operation.insert({'video': 'https://www.youtube.com/embed/dQw4w9WgXcQ'}),
 Operation.insert('\n'),
 ]);
```

And with the new version it should be:

```dart
 final expectedDeltaLinkAndVideoLink = Delta.fromOperations([
 Operation.insert('fdsfsd', {'link': 'https://www.macrumors.com/'}),
 Operation.insert('\n'),
 Operation.insert({'video': 'https://www.youtube.com/embed/dQw4w9WgXcQ'}),
 Operation.insert('\n'),
 ]);
```

Sorry for these errors. When I made the `PR` to update to the latest version I made sure to do the test, but it did not throw errors at any time nor did it show conflicts. It's now that I notice this

**Comment by EchoEllet** [comment]
> Sorry for these errors. When I made the PR to update to the latest version I made sure to do the test, but it did not throw errors at any time nor did it show conflicts. It's now that I notice this

No need to be sorry, take your time.

**Comment by CatHood0** [comment]
I already made a PR to solve this issue with tests

**Comment by singerdmx** [comment]
weird, why are tests still failing?

**Comment by EchoEllet** [comment]
> weird, why are tests still failing?

This branch is outdated with the `master` branch that has the test fixes.

**Comment by singerdmx** [comment]
@Alspb Please rebase

**Pull request merged**
