### PR TITLE
Rebuild editor when keyboard is already open

### PR DESCRIPTION
**Pull request by friebetill**
If the keyboard is already open, but the editor thinks that the
keyboard is not open, the text will not be updated when writing.

This can easily happen if one has a `TabBarView` with two children,
each with an `QuillEditor`, see the video and code for an example:

<details><summary>Video</summary>

https://user-images.githubusercontent.com/10923085/112652803-196b7c80-8e4e-11eb-8596-12ed42d71876.mov

</details>

<details><summary>Example</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_quill/widgets/controller.dart';
import 'package:flutter_quill/widgets/editor.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late QuillController _controller1;
  late QuillController _controller2;

  @override
  void initState() {
    _controller1 = QuillController.basic();
    _controller2 = QuillController.basic();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 2,
        child: Scaffold(
          appBar: AppBar(
            title: Text('Flutter Quill tabs demo'),
            bottom: TabBar(
              tabs: [
                Tab(text: 'First'),
                Tab(text: 'Second'),
              ],
            ),
          ),
          body: TabBarView(
            children: [
              QuillEditor.basic(controller: _controller1, readOnly: false),
              QuillEditor.basic(controller: _controller2, readOnly: false),
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>

### CODE REVIEW

**Comment by singerdmx** [comment]
Not sure this is right

**Comment by singerdmx** [comment]
This may bring back old issue

**Comment by singerdmx** [comment]
See https://github.com/singerdmx/flutter-quill/commit/08ed4c3c85b2bf38cb9631339f81d5ab68edc114

**Comment by singerdmx** [comment]
I'm afraid this change will break single editor behavior.
You are trying to solve multiple editors. Maybe you can pass additional parameter to handle it specially.
DO NOT DO this for multiple editors

**Comment by singerdmx** [comment]
Old issue is https://github.com/singerdmx/flutter-quill/issues/39

Make sure it does not come back

**Comment by singerdmx** [comment]
When keyboard is on, we don't want to call `_onChangeTextEditingValue`
Because it triggers scrollController to scroll

**Comment by singerdmx** [comment]
@friebetill is it possible to associate keyboard with some globalkey? See https://github.com/singerdmx/flutter-quill/pull/113

So you have two keyboards?

**Comment by friebetill** [comment]
I did not have time yesterday, but I will look at the problem again in detail today! Thanks for the reference to the issue #39.

> So you have two keyboards?

I have exactly the problem seen in the video. I have a TabBarView with two editors and switching between the tabs makes the editor not rebuilding when the keyboard stays open.

**Comment by friebetill** [comment]
Okay I have now solved the error by setting the initial visibility of the keyboard depending on whether the keyboard is visible.

Regarding the commit https://github.com/singerdmx/flutter-quill/commit/08ed4c3c85b2bf38cb9631339f81d5ab68edc114:
You solved the editor jumping with this code:
Screenshot 2021-03-27 at 16 46 48
In the code the offset to the point where the selection is visible is calculated. If the selection is not visible, the editor is scrolled until the selection is visible. This prevents jumping, since now no more jumps are made when the selector is visible. 

I don't quite understand the other changes with the `KeyboardListener`, they don't help solve the problem. As far as I can see, we could remove the changes. But maybe I missed something, do you remember why you added the changes?

---
 
**A approach that I have also tried:**
The approach with keys does not work either. But I found out that the state is always destroyed when navigating between tabs. [The problem can be solved](https://stackoverflow.com/questions/49087703/preserving-state-between-tab-view-pages) by implementing `AutomaticKeepAliveClientMixin`. Now the state is preserved, but there is still the problem that the state of the second tab is not created until one navigate there once. That means, there is still the error, that if you open the keyboard in the first tab and then navigate to the second tab, the KeyboardListener of the second tab did not hear the opening of the keyboard. Therefore, unfortunately, this is not a solution.

**Comment by singerdmx** [comment]
KeyboardListener is to detect if keyboard is already open. If true, don't scroll at all

**Comment by singerdmx** [comment]
Actually, it is for the first time you open keyboard, we want to trigger scroll

**Comment by singerdmx** [comment]
The issue is described here https://github.com/memspace/zefyr/issues/485

**Comment by singerdmx** [comment]
basically when keyboard is from invisible to become visible, we want to scroll

**Pull request merged**
