### PR TITLE
merge dev into master

### PR DESCRIPTION
**Pull request by zhaoce**

### CODE REVIEW

**Comment by singerdmx** [comment]
conflict

**Comment by zhaoce** [comment]
> conflict

**Comment by zhaoce** [comment]
I don't know why this file keeps conflicting, I'll close this pr first.

Conflicting files
lib/src/widgets/keyboard_listener.dart

**Comment by zhaoce** [comment]
> I don't know why this file keeps conflicting, I'll close this pr first.
> 
> Conflicting files
> lib/src/widgets/keyboard_listener.dart

@singerdmx resolved!

**Comment by singerdmx** [comment]
Change 96 files ?!

**Comment by singerdmx** [comment]
Please stop this

**Comment by singerdmx** [comment]
Just cherry pick the SINGLE change you want!!!

**Comment by zhaoce** [comment]
> Just cherry pick the SINGLE change you want!!!

Ok, I just merged master to dev, and then auto generated so many changes when merged back from dev

**Pull request closed without merging**
