### PR TITLE
Fixed Flutter Quill Not Working With Xcode 14 Beta or iOS 16 Beta

### PR DESCRIPTION
**Pull request by garv-shah**
@singerdmx i got the package uploaded to pub [here](https://pub.dev/packages/youtube_player_flutter_quill/versions/8.2.0) :)
Sorry it took so long, was figuring out how pub worked, hopefully this can be published successfully

### CODE REVIEW

**Comment by singerdmx** [comment]
Thanks! Yes it is tricky 😉

**Comment by singerdmx** [comment]
* line 4, column 1 of lib/src/widgets/embeds/youtube_video_app.dart: This package does not have youtube_player_flutter in the `dependencies` section of `pubspec.yaml`.
    ╷
  4 │ import 'package:youtube_player_flutter/youtube_player_flutter.dart';
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
Sorry, your package is missing a requirement and can't be published yet.
For more information, see: https://dart.dev/tools/pub/cmd/pub-lish.

**Comment by garv-shah** [comment]
ahh, sorry
one second

**Comment by singerdmx** [comment]
No problem

**Comment by singerdmx** [comment]
fixed https://github.com/singerdmx/flutter-quill/commit/bf40b213161263ea30c117521152fa4a1821d256

**Comment by singerdmx** [comment]
published https://pub.dev/packages/flutter_quill/versions/5.2.3

**Pull request merged**
