### PR TITLE
Changes to flutter_quill_extensions before update

### PR DESCRIPTION
**Pull request by Jon-Salmon**
Not for merging yet, but for tracking `flutter_quill_extensions` pre-releases

### CODE REVIEW

**Comment by singerdmx** [comment]
@Jon-Salmon could you please add me and @freshtechtips as collaborator for the package flutter_quill_extentions ?

**Comment by Jon-Salmon** [comment]
I'm happy to but will need to move it to another publisher first. Do you have a publisher setup that this would work for or do we need to look into creating a new publisher?

**Comment by singerdmx** [comment]
@freshtechtips how about your publisher?

**Comment by freshtechtips** [comment]
> @freshtechtips how about your publisher?

Not sure what you mean but I already have a publisher I need @Jon-Salmon to review the last pull request I sent
It doesn't make difference to me if you are the publisher or I'm as long it's working

**Comment by singerdmx** [comment]
@Jon-Salmon want to move it to another publisher and I suggest to use your publisher

**Comment by freshtechtips** [comment]
> @Jon-Salmon want to move it to another publisher and I suggest to use your publisher

Fine by me

**Comment by singerdmx** [comment]
@freshtechtips you don't have a publisher for https://pub.dev/packages/fresh_quill_extensions ?

**Comment by singerdmx** [comment]
@freshtechtips have you created a publisher yet?

**Comment by freshtechtips** [comment]
> @freshtechtips have you created a publisher yet?

I already have and I created it for fresh_quill_extenstions

**Comment by freshtechtips** [comment]
> https://pub.dev/packages/fresh_quill_extensions

I called it [Fresh Platform](https://pub.dev/publishers/freshplatform.net/packages)

**Comment by singerdmx** [comment]
@Jon-Salmon you can use [Fresh Platform](https://pub.dev/publishers/freshplatform.net/packages) thanks

**Comment by Jon-Salmon** [comment]
@freshtechtips I've sent you an email requesting access.

**Comment by freshtechtips** [comment]
> @freshtechtips I've sent you an email requesting access.

Sure, just a moment

**Comment by freshtechtips** [comment]
> @freshtechtips I've sent you an email requesting access.

I already sent you invite to be a member of the publisher but I forgot to mention that in here

**Comment by freshtechtips** [comment]
> @Jon-Salmon you can use [Fresh Platform](https://pub.dev/publishers/freshplatform.net/packages) thanks

The LICENSE in the project hasn't updated since 2020, and the year is still 2020 in the file

do you suggest updating it??

**Pull request closed without merging**
