### PR TITLE
Fixed bottom toolbar and added Web files

### LINKED ISSUE #16: [Feature Request] Would like to work on Web Support for this plugin
As mentioned [here](https://1o24bbs.com/t/200-bounty-for-implementing-web-support-of-flutter-quill/26179), I would like to try and submit a PR to enable web support for this plugin

### PR DESCRIPTION
**Pull request by rish07**
- This PR will close #16 
- Fixed null error because of a null attribute in heading style in the bottom toolbar in toolbar.dart

### CODE REVIEW

**Review by singerdmx — COMMENTED** [review]
Maybe update README for a web section
such as how to run app demo in web

**Comment by singerdmx** [comment]
Code looks great!

**Comment by rish07** [comment]
Hey @singerdmx, is there a discord or slack community that I can join to talk to you related to doubts while enabling Web support for this plugin?

**Comment by singerdmx** [comment]
> Hey @singerdmx, is there a discord or slack community that I can join to talk to you related to doubts while enabling Web support for this plugin?

Yes, please join Slack Group https://join.slack.com/t/bulletjournal1024/shared_invite/zt-fys7t9hi-ITVU5PGDen1rNRyCjdcQ2g

**Comment by rish07** [comment]
I have joined and sent a message on general can you reply back so I get your ID?

**Pull request merged**
