### PR TITLE
Feat: New way to get Delta from HTML inputs

### LINKED ISSUE #1922: Font Color doesn't show correctly, all text will be black, and can't apply a font color for text.
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.4.1

### Steps to reproduce

1, I'm getting html text from an API: <p>\n  <span style=\"font-size: small;\">\n    SDS Attached? &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Pics Attached?\n    <br/>\n    <br/>\n    Air? &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ocean?\n    <br/>\n    <br/>\n    Qty:\n    <br/>\n    <br/>\n    Battery Installed?\n    <br/>\n    <br/>\n    <br/>\n    <span style=\"color:#B22222; font-size: 12px;\">* FAVOR NO RESPONDER A ESTE CORREO</span>\n    <br/>\n  </span>\n</p>\n

2.I'm parsing this text width Document.fromHtml(htmlText), the text shows rightly but not the red color for last line.
3. I'm sending the text to the API to send and email parsing with quillController.document.toDelta().toHtml() using quill_html_converter.dart, the html text is right but it doesn't has the color tag.

### Expected results

want to see and send the last line in red color

### Actual results

currently the color shown is black

### Code sample

<details><summary>Code sample</summary>

```dart
var html = widget.emailBody?.mailBody ??
        "<p>\n  <span style=\"font-size: small;\">\n    SDS Attached? &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Pics Attached?\n    <br/>\n    <br/>\n    Air? &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ocean?\n    <br/>\n    <br/>\n    Qty:\n    <br/>\n    <br/>\n    Battery Installed?\n    <br/>\n    <br/>\n    <br/>\n    <span style=\"color:#B22222; font-size: 12px;\">* FAVOR NO RESPONDER A ESTE CORREO</span>\n    <br/>\n  </span>\n</p>\n";
    quillController2.document = Document.fromHtml(html);

// Quill Editor
Column(
                children: [
                  QuillToolbar.simple(
                      configurations: QuillSimpleToolbarConfigurations(
                          controller: quillController2)),
                  SingleChildScrollView(
                    child: Container(
                        height: 380,
                        width: 550,
                        decoration: const BoxDecoration(color: Colors.white),
                        child: QuillEditor.basic(
                            configurations: QuillEditorConfigurations(
                                controller: quillController2))),
                  ),
                ],
              )

// Send mail button
CustomSaveButton(
                text: 'Send Email',
                active: true,
                onPressed: () async {
                  String htmlContent =
                      quillController2.document.toDelta().toHtml();
                  context.pop();
                  ref
                      .read(whTabControllerProvider.notifier)
                      .sendComplianceEMail(
                          emailParams: ComplianceMailModel(
                              from: 'warehouse@lotrading.com',
                              to: controllers[0].text,
                              cc: controllers[1].text,
                              bcc: controllers[2].text,
                              subject: controllers[3].text,
                              msg: htmlContent,
                              attachmentPaths: ref
                                  .watch(whTabControllerProvider)
                                  .attachmentList));
                },
              )
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### LINKED ISSUE #1945: Converting from HTML not rendering the videos and the iframes
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

How do I go about this, I want to convert from HTML, the text and the Images are working but the videos and the iframes were not showing at all.

### LINKED ISSUE #1947: Html render issue with sup and sub
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

_No response_

### Steps to reproduce

1 - convert data to html and save it
2- return data from html

### Expected results

Screenshot_1719219662

### Actual results

Screenshot_1719219545

### Code sample

 controller = QuillController(
                    document: Document.fromHtml(
                        bloc.questions!.question[bloc.currentQuestion].name),
                    selection: const TextSelection.collapsed(offset: 0));

and json  name: "<p>Question 7<sup>2</sup><br/>H<sub>2</sub>O</p>",

### Screenshots or Video

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by CatHood0**
## Description

The old implementation was changed to obtain a Delta from an HTML input, where attributes that were useful for other people were lost (almost always) because Markdown did not support them (such as subscript, superscript, color, background, video, underline).

Now with this implementation (using [flutter_quill_delta_from_html](https://pub.dev/packages/flutter_quill_delta_from_html)), we can not only get a Delta with all the attributes currently supported, but also added support for rendering custom HTML for that becomes a valid Quill js Operation

## Related Issues

*Related #1982*
*Fix #1947*
*Fix #1945*
*Fix #1922*

## Checklist

- [x] I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the package version in `pubspec.yaml` files.
- [x] All existing and new tests are passing.
- [x] I have run the commands in `./scripts/before_push.sh` and it all passed successfully

## Breaking Change

Does your PR require developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Review by singerdmx — APPROVED** [review]

**Comment by ellet0** [comment]
If the markdown converter package is no longer needed, I suggest extracting the changes made on this repository and sending it to the upstream repository.

We still need it for Markdown pasting.

The `html2md` package is not required as a dependency, though.

**Comment by singerdmx** [comment]
Do you mean this https://github.com/singerdmx/flutter-quill/pull/1985 ?

**Comment by ellet0** [comment]
> Do you mean this https://github.com/singerdmx/flutter-quill/pull/1985 ?

Yes.

**Comment by singerdmx** [comment]
Why are those dependencies in the core?
Shouldn't they be in https://github.com/singerdmx/flutter-quill/blob/master/quill_html_converter/pubspec.yaml ?

**Comment by ellet0** [comment]
> flutter_quill_delta_from_html

As a suggestion, We can extract the required parts that are not specific to Flutter from `flutter_quill` so your package can use them to extend the support on Dart frameworks outside of Flutter?

This will allow using the converter on the server side.

**Comment by ellet0** [comment]
> Why are those dependencies in the core?
> Shouldn't they be in https://github.com/singerdmx/flutter-quill/blob/master/quill_html_converter/pubspec.yaml ?

Previously, we needed them for the rich text pasting feature. Some of them were required in the HTML converter, though I duplicated them since we only need to convert from HTML to avoid adding extra dependencies on `flutter_quill` by requiring `quill_html_converter`.

**Comment by ellet0** [comment]
> Why are those dependencies in the core?
> Shouldn't they be in https://github.com/singerdmx/flutter-quill/blob/master/quill_html_converter/pubspec.yaml ?

Previously, we needed them for the rich text pasting feature. Some of them were required in the HTML converter, though I duplicated them since we only need to convert from HTML to avoid adding extra dependencies on `flutter_quill` by requiring `quill_html_converter`.

**Comment by CatHood0** [comment]
> We can extract the required parts that are not specific to Flutter from flutter_quill so your package can use them to extend the support on Dart frameworks outside of Flutter?

No problem! My implementation is made to be used by everyone, however, I did not take this case into account. If you want to extract only the required parts, there is no problem from my side

**Comment by ellet0** [comment]
> No problem! My implementation is made to be used by everyone, however, I did not take this case into account. I'll take your suggestion for the next update from my package

Though this is not a technical issue, The package is called `flutter_quill_delta_from_html` which might confuse users in case they use the package for Dart projects that are not Flutter, you don't have to solve this since it's not an issue though there are a few suggestions:

1. Discounting the package and publishing it again with a different name since usually, the developer will use `flutter_quill` which already has this functionality that depends on `flutter_quill_delta_from_html `. 

2. Move the package to this repo directly for seamless integration with the project, so we can automate the releases with CI, and tests, making it a bit easier to contribute to the package code and make some changes in the same PR without sending two different PRs to different repositories, bug report, feature request etc...

If we introduce breaking changes (10.0.0), we can update the `quill_delta_from_html` package so it has the same version as the other packages. Eliminate the need for having a table for the compatible version and managing them manually.

Can be more future-proof, [Kotlin 2.0.0](https://kotlinlang.org/docs/whatsnew20.html) did something similar by moving the Compose Compiler in the Kotlin repository instead of being two separate projects. Eliminating the need for having a table for the compatible versions and having to also manage them.

Or maybe we can move the code of this package directly to a source directory in `flutter_quill` since it depends on it though this will make it a bit harder for projects that use it for the backend or non-Flutter projects that use Dart.

In case you're interested, I would recommend creating a discussion to plan things before releasing them since we will have two packages, for converting to and from HTML.

**Comment by ellet0** [comment]
When testing this change, I had a build failure:

```console
Invalid depfile: /Users/ellet/Developer/playground/framework_based/flutter/flutter-quill/example/.dart_tool/flutter_build/d81a32a1e04fb31b0404583761919a5b/kernel_snapshot.d
Error: Couldn't resolve the package 'flutter_quill_delta_from_html' in 'package:flutter_quill_delta_from_html/flutter_quill_delta_from_html.dart'.
../lib/src/models/documents/delta_x.dart:1:8: Error: Not found: 'package:flutter_quill_delta_from_html/flutter_quill_delta_from_html.dart'
import 'package:flutter_quill_delta_from_html/flutter_quill_delta_from_html.dart';
       ^
../lib/src/models/documents/delta_x.dart:25:48: Error: Type 'CustomHtmlPart' not found.
  static Delta fromHtml(String htmlText, {List<CustomHtmlPart>? customBlocks}) {
                                               ^^^^^^^^^^^^^^
../lib/src/models/documents/delta_x.dart:25:48: Error: 'CustomHtmlPart' isn't a type.
  static Delta fromHtml(String htmlText, {List<CustomHtmlPart>? customBlocks}) {
                                               ^^^^^^^^^^^^^^
../lib/src/models/documents/delta_x.dart:26:25: Error: Method not found: 'HtmlToDelta'.
    final htmlToDelta = HtmlToDelta(customBlocks: customBlocks);
                        ^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Aflutter_quill_delta_from_html%2Fflutter_quill_delta_from_html.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34)
#1      asFileUri (package:vm/kernel_front_end.dart:752)
#2      writeDepfile (package:vm/kernel_front_end.dart:892)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:680)
<asynchronous suspension>
#4      starter (package:frontend_server/starter.dart:101)
<asynchronous suspension>
#5      main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13)
frontend_server_starter.dart:13
<asynchronous suspension>

Target kernel_snapshot failed: Exception

Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **
```

That can be fixed by:

```shell
(cd example && flutter clean)
flutter pub get
```

This issue will only occur while development with the `example`, if we make changes to the packages, we will have to manually execute `flutter pub get` in the `example` directory.

**Comment by CatHood0** [comment]
> The package is called flutter_quill_delta_from_html which might confuse users in case they use the package for Dart projects that are not Flutter

I don't know why I wasn't notified of this comment sooner.

Now that you mention it, I also thought about that at the beginning, only since I had an error with another package with a similar name, to avoid breaking my brain, I better just name it whatever seemed convenient. However, now I decided that it was better to name it in a simple way without including `flutter_quill` since the package is responsible for using a valid `Delta` format for `Quill Js` and `flutter_quill` . I'm still deciding whether to remove the `line-height` parsing because `Quill Js` originally doesn't support this feature by default.

**Comment by EchoEllet** [comment]
> I don't know why I wasn't notified of this comment sooner.

Seems to be notifications issue.

>  I also thought about that at the beginning, only since I had an error with another package with a similar name, to avoid breaking my brain

<details>
<summary>Naming can be challenging</summary>

Sometimes it takes more time to decide the name than it takes to write the actual functionality in addition to the tests.

image

</details>

**Pull request merged**
