### PR TITLE
Image embedding tweaks

### PR DESCRIPTION
**Pull request by MacDeveloper1**
- Add `MediaButton` which is intened to superseed the `ImageButton` and `VideoButton`. Only image selection is working.
- Implement image insert for web (image as base64)

### CODE REVIEW

**Comment by MacDeveloper1** [comment]
Hi @singerdmx. I need your help in merge. It looks while I edited `flutter_quill_extensions/pubspec.yaml` is was edited on backend side.

**Comment by singerdmx** [comment]
can you update changelog?

**Comment by MacDeveloper1** [comment]
> can you update changelog?

Done.

**Comment by MacDeveloper1** [comment]
@Jon-Salmon, please update the version of [flutter_quill_extensions](https://pub.dev/packages/flutter_quill_extensions).

**Comment by Jon-Salmon** [comment]
@MacDeveloper1 Unable to publish due to the dependency you added `universal_ui` not supporting null safety. Please resolve
```
  package:universal_ui is not opted into null safety in its pubspec.yaml:
    ╷
  5 │   sdk: '>=2.7.0 <3.0.0'
    │        ^^^^^^^^^^^^^^^^
    ╵
```

**Pull request merged**
