### PR TITLE
added formula to sample data json

### PR DESCRIPTION
**Pull request by garv-shah**

### CODE REVIEW

**Comment by singerdmx** [comment]
OK I wasn't clear about this.
You need to add corresponding code to handle this attribute. Otherwise the editor will crash.

**Comment by garv-shah** [comment]
almost already done in my fork from above, but I can't figure out where the attributes for embeds are, they don't seem to be defined in the same `attribute.dart` file as the rest. would you please be able to take a look [here](https://github.com/singerdmx/flutter-quill/compare/master...garv-shah:flutter-quill:master) at what I changed and help me out to where to add this?

**Comment by singerdmx** [comment]
I think you can follow `codeBlock`

image

**Comment by garv-shah** [comment]
but that scope is inside block, according to the quilljs documentation, this should be under the embed scope
i'd either have to follow image or video, but i can't find the line similar to 317 in `attribute.dart` for codeBlock

**Comment by singerdmx** [comment]
Yes, it should be embed, not codeblock

**Comment by singerdmx** [comment]
Then you don't need to define new attribute since it is embed

**Comment by garv-shah** [comment]
oh nice, so should I submit a PR, and we can go back to https://github.com/singerdmx/flutter-quill/issues/898#issuecomment-1203351039 ?

**Comment by singerdmx** [comment]
Ok it is new button anyway 
If it has issue other people can help fix

**Comment by singerdmx** [comment]
Worst case you hide it

**Comment by garv-shah** [comment]
cool, thanks!

**Pull request closed without merging**
