### PR TITLE
Fix crash with inserting text from contextMenuButtonItems #1724

### PR DESCRIPTION
**Pull request by EgorK0rshun**
## Description

Fix crash with inserting text from contextMenuButtonItems for 32-bit CPU Type  https://github.com/singerdmx/flutter-quill/issues/1724

## Related Issues

Fix crash with inserting text from contextMenuButtonItems  https://github.com/singerdmx/flutter-quill/issues/1724

- [x] I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [ ] I did not modify the `CHANGELOG.md` nor the plugin version in `pubspec.yaml` files.
- [x] All existing and new tests are passing.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by ellet0** [comment]
Hi, did you change the CHANGELOG.md and version.dart at the root folder and run the script regenrate versions?

**Comment by EgorK0rshun** [comment]
@ellet0, Hi, the script didn't work on my laptop right now. I changed everything manually

**Comment by EgorK0rshun** [comment]
there is no difference between the code available in the request

**Comment by EgorK0rshun** [comment]
I'll recreate it.

**Pull request closed without merging**
