### PR TITLE
Scale leading widgets based on paragraph font size

### LINKED ISSUE #1203: [Feature request] Scale checkboxes with line height
# Current behaviour
Checkboxes have a fixed size regardless of the font size. This means when the font size is big (e.g. to be readable on mobile), the checkboxes are still small and hard to tap.

# Desired behaviour
Bigger text has correspondingly bigger checkboxes and vice versa.

# Screenshots 
Screenshot_20230507-182807
Screenshot_20230507-182845

### PR DESCRIPTION
**Pull request by adil192**
Resolves #1203

Note that this PR doesn't account for differing font sizes on the same line, but just uses the default paragraph font size.

### CODE REVIEW

**Comment by singerdmx** [comment]
Could you please update the version and changelog?

**Comment by adil192** [comment]
I'll bump the version once I've tested properly :)

**Comment by adil192** [comment]
image
Currently I want to line up the numbered/unordered lists better

**Comment by adil192** [comment]
image
Done!

**Comment by adil192** [comment]
@singerdmx Are you happy with the bullet/number points being centered in the leading column, or would you prefer them to be aligned at the end?

**Comment by adil192** [comment]
image

(End-aligned)

**Pull request merged**
