### PR TITLE
fixed #1835 Embed Reloads on Cmd Key Press

### LINKED ISSUE #1835: Embed Reloads on Cmd Key Press in google chrome
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.4

### Steps to reproduce

1. Open the example app on a macOS device.
2. Navigate to a part of the app where embedded content (e.g., a video) is displayed.
3. Press the Cmd key.
4. Observe that the embedded content reloads.

### Expected results

The embedded content should not reload or refresh when the Cmd key is pressed, as this disrupts the user experience.

### Actual results

Pressing the Cmd key causes the embedded content to reload.

### Code sample

Check example app

### Screenshots or Video

https://github.com/singerdmx/flutter-quill/assets/149594833/2c02ac39-d464-4922-8e22-391c4703b946

### Logs

_No response_

### PR DESCRIPTION
**Pull request by li8607**
## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/singerdmx/flutter-quill/issues). Indicate, which of these issues are resolved or fixed by this PR.*

*e.g.*
- *Fix #123*
- *Related #456*

## Checklist

- [x] I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [x] I titled the PR using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0).
- [x] I did not modify the `CHANGELOG.md` nor the package version in `pubspec.yaml` files.
- [x] All existing and new tests are passing.
- [x] I have run the commands in `./scripts/before_push.sh` and it all passed successfully

## Breaking Change

Does your PR require developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate that with a `!` in the title as explained in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0)).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by EchoEllet** [comment]
Thank you for your contributions. This was a critical bug that made the editor unusable on desktop platforms.

**Comment by li8607** [comment]
Thank you for your feedback. Could you please provide more details? I tested it on macOS and did not encounter any issues.

**Comment by singerdmx** [comment]
@EchoEllet do you mean this change broke something?

**Comment by singerdmx** [comment]
I see it does break tests

**Comment by EchoEllet** [comment]
> Could you please provide more details? I tested it on macOS and did not encounter any issues.

I meant your PR fixed this critical bug, though we should test it on other desktop platforms and more use cases since we depend on manual texting. 

> do you mean this change broke something?

I haven't tested it or saw the code yet thoufh.

**Comment by singerdmx** [comment]
The failure is just code formatting 
@li8607 please format code

**Pull request merged**
