### PR TITLE
Sound null safety migration

### LINKED ISSUE #69: Flutter Quill does not support "null safety"
I have been facing issue, when I run flutter Quill on my flutter web app 

quill Issue

Please shift your package to null safety so that we can use it 
Thank you For Helping

### PR DESCRIPTION
**Pull request by MillerAdulu**
This PR attempts to resolve #69.

Some of the issues involved were upgrading some depended packages to null-safety and localizing some packages which are no longer maintained. 

One error that stands out is, it's not usable because of a GlobalKey issue in the widget tree once QuillEditor.basic is added to a page

How to try out the package. In `pubspec.yaml`

```yaml
flutter_quill: 
    git:
      url: https://github.com/singerdmx/flutter-quill.git
      ref: e1f3f9aa95dd32f9490222d14a7be3969696f351
```

### CODE REVIEW

**Comment by singerdmx** [comment]
Maybe break it into smaller changes?

**Comment by singerdmx** [comment]
> One error that stands out is, it's not usable because of a GlobalKey issue in the widget tree once QuillEditor.basic is added to a page

What does it break?

**Comment by singerdmx** [comment]
It seems that you need to resolve conflicts.
Please let us know if it is safe to accept your MR. I wonder if it breaks anything

**Comment by MillerAdulu** [comment]
> > One error that stands out is, it's not usable because of a GlobalKey issue in the widget tree once QuillEditor.basic is added to a page
> 
> What does it break?

I am not sure yet. After adding the widget to the page, it throws a GlobalKey duplicate error. It's been a long weekend trying to migrate everything especially the dependent packages so I am yet to try again. 

I will try again to see if I can track down the error.

**Comment by MillerAdulu** [comment]
> Maybe break it into smaller changes?

This was the initial plan. But after running the migration tool and resolving errors, the rabbit hole goes deeper until everything is fixed before it can be tried.

**Comment by singerdmx** [comment]
Thanks! We will accept the MR once you confirm it is safe to accept

**Comment by rfmanuj** [comment]
If it helps you, it seems there is a problem with filesystem_picker:
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:filesystem_picker

A null safe version of this package will be releasesd in the next days: https://github.com/andyduke/filesystem_picker/issues/14

**Comment by andyduke** [comment]
> 
> 
> If it helps you, it seems there is a problem with filesystem_picker:
> Error: Cannot run with sound null safety, because the following dependencies
> don't support null safety:
> 
>     * package:filesystem_picker
> 
> 
> A null safe version of this package will be releasesd in the next days: [andyduke/filesystem_picker#14](https://github.com/andyduke/filesystem_picker/issues/14)

[filesystem_picker](https://pub.dev/packages/filesystem_picker/versions/2.0.0-nullsafety.0) now supports null safety.

**Comment by MillerAdulu** [comment]
@singerdmx I am not sure this was ready for merging just yet. 

I am still trying to test it in an app. If you have, then it's fine, but I had fixed the errors for purposes of testing as I am pulling the package as a git dependency in the app I am testing it on.

**Pull request merged**
