### PR TITLE
Feature/headers dropdown

### PR DESCRIPTION
**Pull request by freshtechtips**
Carry the changes from [#1575](https://github.com/singerdmx/flutter-quill/pull/1575)
- #1575

### CODE REVIEW

**Comment by freshtechtips** [comment]
@MacDeveloper1 I will merge this but I still need you to review the new dropdown button because it doesn't use your newly created configuration class, or we can just remove unused properties

**Comment by MacDeveloper1** [comment]
>I will merge this but I still need you to review the new dropdown button because it doesn't use your newly created configuration class, or we can just remove unused properties

Am I right and you also created a dropdown butons for headers? It is true I didn't notice it.

My widget is just a new representation of old butons style.

**Comment by freshtechtips** [comment]
> >I will merge this but I still need you to review the new dropdown button because it doesn't use your newly created configuration class, or we can just remove unused properties
> 
> Am I right and you also created a dropdown butons for headers? It is true I didn't notice it.
> 
> My widget is just a new representation of old butons style.
> 
> 

Yes, but I carried your changes with the new button

**Comment by MacDeveloper1** [comment]
@ellet0  Unfortunately you did not my changes in new button. You cut too many used parameters #1616 . Those parameters were taken from similar dropdowns for font families and font sizes. Please restore the button as is.

**Comment by ellet0** [comment]
> @ellet0  Unfortunately you did not carry my changes in new button. You cut too many used parameters (#1616) . Those parameters were taken from similar dropdowns for font families and font sizes. Please restore the button as is.

I cut the unused parameters to avoid confusion 

You used the dropdown button from material 2 and not 3, and the parameters are different. This is why I asked you to complete the rest

It's just a parameters ans that's all you don't have to do much

**Pull request merged**
