### PR TITLE
Major update 6

### PR DESCRIPTION
**Pull request by freshtechtips**
- The Quill editor and toolbar configurations are now refactored in one single class for each one
- After changing one of the checkbox list values the controller will not request the keyboard focus by default
- We have moved the configurations of the toolbar and the editor directly into the widget but we are still using inherited widgets internally
- Fixes to some of the code after the refactoring

More changes...

### CODE REVIEW

**Comment by freshtechtips** [comment]
**flutter_quill_extensions** will fail again, we probably need to publish the package to pub.dev and then update things from **flutter_quill_extensions**, also we should publish the flutter_quill_extensions updates to pub.dev

**Comment by singerdmx** [comment]
Another option is that you publish the package instead

**Comment by freshtechtips** [comment]
> Another option is that you publish the package instead

Are we talking about flutter_quill_extensions?? because you told me @Jon-Salmon has access to the publishing

**Comment by singerdmx** [comment]
Yes I mean if you don't want to be blocked on that. Create a new package

**Comment by freshtechtips** [comment]
> Yes I mean if you don't want to be blocked on that. Create a new package

Do you mean fork the repository of flutter_quill_extensions??

**Comment by singerdmx** [comment]
Oh pub.dev check url uniqueness? I see. Probably have to work around it

**Comment by freshtechtips** [comment]
> Oh pub.dev check url uniqueness? I see. Probably have to work around it

Still not sure what you mean by this message, is this what you mean by taking a copy of the flutter_quill_extensions publishing it with the new changes, and naming it with a different package name like flutter_quill_extensions_plus or something like that?? just

**Comment by singerdmx** [comment]
Yes

**Comment by freshtechtips** [comment]
> Yes

Fine by me but I think we should tell @Jon-Salmon first about this first
or another option is that we do this temporarily while he/she is not around

**Comment by singerdmx** [comment]
Sure

**Comment by freshtechtips** [comment]
> Sure



> Can't run the example - it shows failed assertion.

I didn't test the example because I decided to test the changes on a real project instead with extra functionality to catch more bugs

but give me a moments to check it...

**Comment by freshtechtips** [comment]
> Can't run the example - it shows failed assertion.



> Can't run the example - it shows failed assertion.

Please clean the project and run it again and make sure to fetch the latest changes and rebase or merge

image

Can't encounter the issue you are facing, consider giving me more details so I can fix it

**Comment by freshtechtips** [comment]
> Hm, it also works for me on Android emulator. But on Linux it fails with pretty large stack trace. If you don't face the error on desktop, I'll put the details here.

if it is related to the Linux binary application building. then I can't fix it right now since this library is not supported for Linux yet as it uses plugins that don't support Linux yet. I will look into that soon but it would be helpful to share more details

**Comment by freshtechtips** [comment]
> Please also take a look at #1288, cause it seems to be connected with images which you're also working on.

Sure, I will checkout tomorrow. But can you upload some images or short video??

**Comment by freshtechtips** [comment]
> > > Please also take a look at #1288, cause it seems to be connected with images which you're also working on.
> > 
> > Sure, I will checkout tomorrow. But can you upload some images or short video??
> Please find the video below:
> 
> insert_link_crash
> 
> 

Thank you for the report

As soon we finish the refactoring and other issues we will work on this one

**Pull request merged**
