### PR TITLE
Pruning unused translations and adding relevant ones

### PR DESCRIPTION
**Pull request by LuchoTurtle**
I was initially going to work on finishing https://github.com/singerdmx/flutter-quill/pull/1403#issuecomment-1737079301 but since https://github.com/singerdmx/flutter-quill/pull/1414 has already been merged, I realised that some translations were needed and other weren't used. So I've refactored it!

In addition, I've added a warning in the `README` file regarding https://github.com/natsuk4ze/gal, as some permissions need to be added to some files (as noted in https://github.com/singerdmx/flutter-quill/pull/1403#discussion_r1335527280).

This should be a quick merge 👌

### CODE REVIEW

**Comment by freshtechtips** [comment]
Thanks

**Comment by freshtechtips** [comment]
@singerdmx I made the message clearer to know if we are saving the image using network or from local storage (cached) just for testing purposes, do we need to have separate translations, one for network saved image and another for storage?

**Comment by LuchoTurtle** [comment]
Yeah, I was a bit hesitant about having specific translations for each scenario, as it doesn't seem really useful to the end user. 
But I kept it because I didn't want to meddle too much with the pre-existing code.

**Comment by freshtechtips** [comment]
> Yeah, I was a bit hesitant about having specific translations for each scenario, as it doesn't seem really useful to the end user. But I kept it because I didn't want to meddle too much with the pre-existing code.

I thought the team would probably change the pull request code but I kept it like this so they could test it directly in the UI

so I remind them to change it if they want to

but it might be helpful to the end user to know if this image is from the cloud, by image URL, or locally in the sandboxed directory of the app

**Pull request merged**
