### PR TITLE
Adds flutter 3.0.0 support for now

### PR DESCRIPTION
**Pull request by myfknoll**
Workaround to run flutter_quill with Flutter 3.0.0

Others can use this for now like:

  flutter_quill:
    git:
      url: https://github.com/myfknoll/flutter-quill.git

### CODE REVIEW

**Comment by singerdmx** [comment]
Sorry NO.
First this is a hack.
Second not all users are using 3.0.0.
So please don't scream just because you are using 3.0.0.

**Comment by deimantasa** [comment]
Hello @singerdmx ,

Could you explain, what's hacky about it? Newest Flutter version (3.0.0) ([which was introduced within last 24 hours](https://docs.flutter.dev/get-started/install/macos)) seems to have introduced some changes which `flutter_quill` does not incorporate yet.

Since Flutter `3.0.0` is on the `stable` branch, `flutter_quill` must incorporate any changes in order to make it work with latest flutter version.

Maybe I misunderstand something here?

**Comment by DmitrySboychakov** [comment]
Actually, this not a hack THAT much, those APIs needed for Scribble ( Stylus input) in Apple platforms and this package not implement this feature. Is it breaking stuff for Flutter 2.X ?

**Comment by singerdmx** [comment]
Please add those in comments 

those APIs needed for Scribble ( Stylus input) in Apple platforms and this package not implement this feature

**Comment by singerdmx** [comment]
Please update yaml

  sdk: ">=2.12.0 <3.0.0"

**Comment by bradcypert** [comment]
@myfknoll Thanks for looking into this. Trying to upgrade to Flutter 3 and this is blocking me. I understand that this isn't finished, but I appreciate you looking into getting this building even if the new features aren't supported yet. Again, thank you. :)

**Pull request merged**
