### PR TITLE
Bug fixes + Provide a way to handle the image errors and use custom image provider

### PR DESCRIPTION
**Pull request by freshtechtips**
Hi, I made a brand-new changes
but it's simple and not as big as the previous one

Features:

1. Allow to use custom image provider
2. Provide a way to handle all the errors of the image widget everywhere even in the preview
3. Add support for image resizing on desktop platforms when forced using the mobile context menu

My purpose of this pul is to add features but I made some improvements in my way.

Issue [#1427](https://github.com/singerdmx/flutter-quill/issues/1427)

Improvements:

- Little code orgnazation
- Fix two bugs, the first one when we use
  ```dart
   mediaPickSettingSelector: (context) async {
                    return MediaPickSetting.Camera;
                  },
  ```
  it will always use a pick image by link instead, this is why I prefer using a switch statement instead of if-else since we add more options all the time and we forgot to handle the others

- The second bug that will happen when we **showCameraButton** to true and we set **onImagePickCallback** but not **onVideoPickCallback**, then nothing will happen, some developers are not interested in using the camera for both photos and recording videos since they are scenarios when you just want to create simple note app or blog for example and you don't want videos, so throw an error will not be a solution, but the current behavior is not throwing an error so I change it to show only take a photo by the camera option if it set and take a photo by the video if set and the dev can always override this by **mediaPickSettingSelector** and **cameraPickSettingSelector**
- The way to check HTTP URL for some functions is handled in a more efficient way
- Improve performance by reducing the number of widgets rebuilt by listening to media query for only the needed things, for example instead of using `MediaQuery.of(context).size`, now we are using `MediaQuery.sizeOf(context)`
- New custom style attributes for platforms other than mobile

```json
[{"insert":{"image":"/Users/ahmedhnewa/Downloads/alrayada.net.png"},"attributes":{"style":"width: 704.8; height: 600.0; "}},{"insert":"\n"}]
```

Suggestions:
- in the flutter_quill_extensions.dart in line 130 in the function List<EmbedBuilder> builders
we have quite a lot of configuration for the image, how about making a class that hold all the configurations for each one, for the image, and all the different widgets
of course, this will require the developers that are overriding the property to update the code of the usage a little bit

- Please read all the todos, most of them I can't decide on my own because that is a community project, and some of them are in flutter_quill_extensions that require changes from flutter_quill but we need to update flutter_quill first so we can get the changes from flutter_quill_extensions, most of them are new custom style attributes

### CODE REVIEW

**Review by singerdmx — APPROVED** [review]

**Comment by singerdmx** [comment]
@Jon-Salmon please have a look

**Comment by freshtechtips** [comment]
> @Jon-Salmon please have a look

I might make more changes, so you might want to consider keeping this pull request open and not accepting the changes just yet, if possible.

**Comment by singerdmx** [comment]
Ok

**Comment by freshtechtips** [comment]
> Ok

I'm adding a new little feature to the desktop which is image resizer support for desktop
but to save some time, can you tell me how to change the width and height of the quill element using the quill controller??

Currently, this logic works only for Mobile:

```dart
final res = getEmbedNode(
                              controller,
                              controller.selection.start,
                            );
                            if (base.isMobile()) {
                              final attr = base.replaceStyleString(
                                getImageStyleString(controller),
                                w,
                                h,
                              );
                              controller
                                ..skipRequestKeyboard = true
                                ..formatText(
                                  res.offset,
                                  1,
                                  StyleAttribute(attr),
                                );
                              return;
                            }
``` 

I tried and I always get an exception of type String which is 'Apply delta rules failed' which is in

```dart
Delta apply(
    RuleType ruleType,
    Document document,
    int index, {
    int? len,
    Object? data,
    Attribute? attribute,
  }) {
    final delta = document.toDelta();
    for (final rule in _customRules + _rules) {
      if (rule.type != ruleType) {
        continue;
      }
      try {
        final result = rule.apply(delta, index,
            len: len, data: data, attribute: attribute);
        if (result != null) {
          return result..trim();
        }
      } catch (e) {
        rethrow;
      }
    }
    throw Exception('Apply delta rules failed');
  }
```

It's a matter of time until I manage this but to help save some time and make this pull request as closed as possible
if possible, can you tell me how to do it in more detail?? the code of flutter_quill is not documented with comments so I need more time

**Comment by singerdmx** [comment]
We can add more logging to help debugging

**Comment by singerdmx** [comment]
This indicates no rule is applied at all

**Comment by singerdmx** [comment]
Apply delta rules failed means no rule is applied

**Comment by freshtechtips** [comment]
> Apply delta rules failed means no rule is applied

I think I'm able to add this little feature

I just need you to tell me if this is a valid quill delta. 

```json
[{insert: {image: /Users/ahmedhnewa/Downloads/example.png}, attributes: {style: width: 412.0; height: 600.0; }}, {insert:
}]
```

It was style: `mobileWidth` and mobileHeight and I'm not sure if this applies to the original quill JSON rules but is it okay to store anything in the attributes of the `mobileWidth` and mobileHeight are not official and extra from this flutter library

but now on desktop, I'm using different attributes which is the width and height key

**Comment by singerdmx** [comment]
mobileWidth is our newly defined special key which is not part of the standard quill delta

**Comment by freshtechtips** [comment]
> mobileWidth is our newly defined special key which is not part of the standard quill delta

1- The attributes key, is it official and part of quill delta??
2- Is it okay to define more properties (width, height)

**Comment by freshtechtips** [comment]
> Desktop should follow web I guess

Not really, The web uses  tag, and desktop can't do that without Chromium or webview

web uses the same one on mobile but as I said previously the context menu of macOS was quite buggy so I added an option for the developer to force the use mobile context menu on desktop, however the resizing option was not working so I had to add it only for mobile

in this pull request, I decided to add support for that too
but we were using mobileWidth and mobileHeight for mobile, what about desktop?? should we use something different like normal width and height like the JSON I sent in my previous message

I'm adding support for desktop context menu resizing image
so it will use properties (width, height) instead of mobile ones and this
is only for desktop and doesn't apply for mobile

**Comment by singerdmx** [comment]
Ok make sense

**Comment by freshtechtips** [comment]
@singerdmx 
@Jon-Salmon 

I know you guys are busy and I have sent pull requests and requested re-reviews too much but you might want to consider re-review the changes again just this time if possible because there are changes made by the others that conflict with this pull request and I had to solve conflicts and commit things to make this project the best it can be with the help of the community, I mean I could squash them but if we're able to get this pull request merged or rejected faster then I will be able to work more on new changes because I do plan to send more pull requests if you don't mind

**Comment by singerdmx** [comment]
LGTM

**Comment by singerdmx** [comment]
@Jon-Salmon I will go ahead and merge this. You can leave comments when you have time so it will be addressed in next PR

**Pull request merged**
