### PR TITLE
Add ability to hide/show Left, Center, Right and Justify alignment buttons

### PR DESCRIPTION
**Pull request by mark8044**
New bools added `showLeftAlignment`, `showCenterAlignment`, `showRightAlignment` and `showJustifyAlignment` allow us to turn those specific buttons on or off.  

This is in reference to issue https://github.com/singerdmx/flutter-quill/issues/449

(this is now my second ever PR!  this is fun..)

### CODE REVIEW

**Comment by singerdmx** [comment]
There is conflict.
You may try to delete your repo and fork again

**Comment by mark8044** [comment]
> There is conflict.
> You may try to delete your repo and fork again

If I delete my fork and re fork from yours, I have to redo all my edits from scratch correct?

**Comment by singerdmx** [comment]
> > There is conflict.
> 
> > You may try to delete your repo and fork again
> 
> 
> 
> If I delete my fork and re fork from yours, I have to redo all my edits from scratch correct?

Yes it is not much

**Comment by mark8044** [comment]
> > > There is conflict.
> > 
> > 
> > > You may try to delete your repo and fork again
> > 
> > 
> > If I delete my fork and re fork from yours, I have to redo all my edits from scratch correct?
> 
> Yes it is not much

Ok I will try now give me about 10 minutes, its all in my head still

**Pull request closed without merging**
